pagopa/developer-portal

apps/nextjs-website/src/components/atoms/UnorderedList/UnorderedList.module.css
apps/nextjs-website/src/components/molecules/GuideCard/GuideCard.tsx

- Fix guide cards text margin, padding and list line-height
Manually

[DEV-726] - Fix guide cards text margin, padding and list line-height

---

apps/nextjs-website/src/components/molecules/ApiSection/ApiSection.tsx

The icon next to "Vai a GitHub" is not rendered.
Pass the icon to the component `ButtonNaked` using the `IconWrapper`
We need to render the icon
Before the fix:
After the fix:

Fix icon for pagoPA API page

---

.github/actions/deploy/action.yaml
apps/nextjs-website/next.config.js
apps/nextjs-website/package.json

According to the[ logs, the `export` command](https://github.com/pagopa/developer-portal/actions/runs/5533397666/jobs/10096867359#step:3:320) is deprecated.
Next suggests to generate the `out` folder (previously generated by the `export` command) [updating the `next.config.js` file](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports).
This should also reduce the build time, because we removed a step during the deploy action, because according to their docs:
> After running next build, Next.js will produce an out folder which contains the HTML/CSS/JS assets for your application.

Remove Next export using next build command

---

apps/nextjs-website/src/pages/[productSlug]/guides/[...productGuidePage].tsx
apps/nextjs-website/src/styles/globals.css

This PR sets guides and manual menu position as sticky and adds scrollbar's style
The menu was disappearing on vertical scroll
Manually
The menu is scrollable independently from the page:
and it's position is sticky and aligned with in page menu on the right:

[DEV-880] - Guides and manual sticky menu

---

apps/nextjs-website/src/components/molecules/ApiSection/ApiSection.tsx

Fix "Go to GitHub" link hover style in ApiSection component
The link was blue on a blue background
Manually

[DEV-777] Fix "Go to GitHub" link style in ApiSection component

---

apps/nextjs-website/src/components/atoms/ApiViewer/ApiViewer.tsx

Add hash router configuration to API components from element
When api pages was reloaded after selecting an endpoint's documentation, next respond with error 404.
User can navagiate to: http://localhost:3000/send/api and after selecting an endpoint from documentation page will show selected endpoint after reloading page
[Screencast from 03-10-2023 17:27:10.webm](https://github.com/pagopa/developer-portal/assets/24475319/9986d592-cac8-4608-8c7b-b3301335c4b8)

[DEV-740] Add hash router to elements

---

.github/actions/branch-up-to-date/action.yaml
.github/actions/link-pr-to-jira-activity/action.yaml

> The best practice to avoid code injection vulnerabilities in GitHub workflows is to set the untrusted input value of the expression to an intermediate environment variable and then use the environment variable using the native syntax of the shell/script interpreter (that is, not ${{ env.VAR }}).
According to GitHub, within `run` or `scripts` in GitHub action, [it is more safe to use the shell syntax to get environment variable](https://github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure/#1-dont-use-syntax-in-the-run-section-to-avoid-unexpected-substitution-behavior).
This should fix the security issue https://github.com/pagopa/developer-portal/security/code-scanning/1

[DEV-975] - Use shell syntax to read environment variables

---

apps/nextjs-website/src/_contents/translations.ts

Fixed mistyped label in the footer (321 instead of 231)
The label was wrong
Manually

[DEV-979] Fixes label 321 as 231 in the footer of site

---

.infrastructure/55_cognito.tf

According to the [OWASP Authentication Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls), a password is weak if it has less than `8` chars.
It should also allow usage of all characters including unicode and whitespace to be considered as a `strong` password.
- Password must contain lowercase character
- Password must contain uppercase character
- Password must contain at least a number
- Password must contain at least a symbol
We want to make sure users' passwords are considered `strong`.
For further details about Cognito user pool's password policy, [check the documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html).
Manually. The policy has been …

[DEV-1010] - Update user pool's password policy

---

apps/cognito-functions/src/__tests__/custom-message-handler.test.ts
apps/cognito-functions/src/custom-message-handler.ts

Send verification email to user even when the trigger is `CustomMessage_ResendCode`.
Before this PR, the user receive a default email coming from Cognito.
- Update unit test
- Handle `CustomMessage_ResendCode` trigger
During sign-up, if a user requests to receive a new verification email, it should receive one.
Unit tests

[DEV-1102] - Handle CustomMessage_ResendCode trigger

---

apps/cognito-functions/src/__tests__/post-confirmation-handler.test.ts
apps/cognito-functions/src/main.ts
apps/cognito-functions/src/post-confirmation-handler.ts

- Send email only when the event is `PostConfirmation_ConfirmSignUp`
- Refactor on file names
We do not want to get an error on `PostConfirmation_ConfirmForgotPassword` event and we only want to send an email when the `PostConfirmation_ConfirmSignUp` occurs
Unit tests

[DEV-1123] - Improve PostConfirmationTriggerEvent handling

---

apps/nextjs-website/src/components/organisms/GitBookContent/components/Table.tsx

Now table cells shows a checkbox if their value is `true` or `false`
DEV-1163
Go to `/pago-pa/guides/saci/3.1.0/specifiche-attuative-dei-codici-identificativi-di-versamento-riversamento-e-rendicontazione/operazione-di-trasferimento-fondi`, scroll to the table, the rightmost column now has checkboxes instead of true and false

[DEV-1163] table checkboxes on true / false values

---

.infrastructure/env/prod/terraform.tfvars

Set X-Robots-Tag to 'all' in prod's terraform variables
The developer Portal's pages are blocked from indexing:
https://www.google.com/search?q=site%3Adeveloper.pagopa.it
Looking at Lighthouse plugin report, it seems to happen because of the X-Robots-Tag rule:

[DEV-1275] Set X-Robots-Tag to 'all' in prod's terraform variables

---

.changeset/modern-berries-hope.md
apps/nextjs-website/src/app/layout.tsx
apps/nextjs-website/src/styles/globals.css

- Used `next/font/google` lib to preload **Tittillium** google font
- Set `font-family: var(--font-titillium-web)!important;`
To avoid layout shifts caused by font loading latency
[screencast-developer.pagopa.it-2023.12.20-10_20_26.webm](https://github.com/pagopa/developer-portal/assets/16854782/0453c30f-cd54-4fe9-ab35-571e0ceaba41)
I checked if the above problem no longer occurs so I tested several pages to see if they had any layout shifts caused by the text.

[DEV-1235] Preload font

---

.changeset/happy-grapes-occur.md
packages/gitbook-docs/src/__tests__/parseContent.test.ts
packages/gitbook-docs/src/markdoc/schema/link.ts
packages/gitbook-docs/src/markdoc/schema/pageLink.ts

Disable the link's title replacing with destination page title and leave it as it was in Gitbook
The team asked to remove the feature
Manually and with `npm run compile; npm run test -w gitbook-docs -- --watch`

[DEV-1089] Fix link's title parsing logic

---

.changeset/six-items-exist.md
apps/cloudfront-functions/src/__tests__/viewer-request-handler.test.ts
apps/cloudfront-functions/src/viewer-request-handler.ts

- handle the trailing slash of the URL in cloudfront function
- add tests
On any developer portal page (excluding the home page), by adding a forward slash at the end of a path, e.g. https://developer.pagopa.it/app-io/guides/io-guida-tecnica → https://developer.pagopa.it/app-io/guides/io-guida-tecnica/ - causes a 404 error.

[DEV-1406] Handle the trailing slash of the URL

---

.github/actions/deploy/action.yaml

Do not fetch from cache when running the deploy website workflow
The deploy didn't get new pages if triggered from Strapi.
The issue is related to the use of the cache step

[DEV-1474] Do not fetch from cache when executing deploy website workflow

---

.github/workflows/code_review_infra.yaml
.github/workflows/deploy_infra.yml

Add concurrency group in workflows
- Add concurrency group
- Do not cancel the in-progress workflows
When several workflows necessitate the use of Terraform (keeping in mind that both `terraform plan` and `terraform apply` require locking), they run concurrently. 
The first workflow executes immediately, while the subsequent ones wait in line.

[DEV-1448] Add concurrency in workflows that are using terraform

---

.github/workflows/check_pr_title.yaml

Now the job is skipped on PRs created by changeset
- Add condition to avoid job execution on particular branch
We do not want the CI is failing on branches created by changeset

[DEV-1456] Add condition on job check_pr_title

---

.changeset/fluffy-rockets-sneeze.md
apps/infrastructure/src/route53.tf

Depends on #753 
- Add some records to allows active campaign to send emails through `developer.pagopa.it` domain
Enable Active Campaign to send emails using `developer.pagopa.it` domain
N/A

[DEV-1489] Add Active Campaign records

---

.changeset/polite-buses-agree.md
apps/nextjs-website/src/lib/strapi/PathReporter.ts
apps/nextjs-website/src/lib/strapi/__tests__/fetchFromStrapi.test.ts
apps/nextjs-website/src/lib/strapi/fetchFromStrapi.ts

- Add a custom `PathReporter`
The current message generated by the built-in 'PathReported' when a decoding error occurs is difficult to read. This PR aims to improve message readability. E.s.:
The message before this PR:
```
Invalid value 1 supplied to : {| data: {| id: string |} |}/data: {| id: string |}/id: string
```
The message after this PR:
```
Invalid value 1 supplied to '/data/id', expected type string
```
Unit Test

[DEV-1545] Add custom PathReporter

---

.changeset/nice-beds-invent.md
apps/infrastructure/src/cloudwatch_metric_alarm.tf

Link all the alarms to a SNS topic.
- Add `alarm_actions` attribute for every alarm
We already have configured the SNS topic and the subscription (that sends emails when a message on a topic has been published).
Now we want to allow the alarms to publish messages on the topic.

[DEV-1345] Link metric alarms to SNS topic

---

.changeset/unlucky-crabs-carry.md
apps/infrastructure/src/iam_policy.tf

- Add `.ssm_parameter_arn` parameters to `ecs_task_execution` policy 
The role used to execute the strapi application needs permissions to fetch the new secrets
N/A

[DEV-1562] Add cms_google_* parameters to ecs_task_execution

---

.changeset/itchy-seas-jam.md
apps/nextjs-website/src/app/[productSlug]/guides/[...productGuidePage]/page.tsx

- add paddings
the title was very close to the menu
Manually. Go to any `Guide e Manuali` page.

[DEV-1321] Increase the distance between the menu and title of guides and manuals

---

.changeset/bright-balloons-sparkle.md
apps/nextjs-website/src/components/atoms/GuideMenu/Menu.tsx

Restore scroll position of guide menu after navigation.
Depends on #840 
Guide menu scrolls to the top after click on a menu item
Open any guide, click on any menu item, and you'll see that the menu's scroll position is preserved

[DEV-1405] Preserve scroll position of guide menu

---

.changeset/cold-ads-mate.md
apps/nextjs-website/src/editorialComponents/EContainer/EContainer.tsx
apps/nextjs-website/src/editorialComponents/Newsroom/Newsroom.tsx

Align news showcase on homepage
The news showcase was misaligned with the rest of the homepage
Manually

[DEV-1508]: align news showcase on homepage

---

.changeset/stale-goats-attack.md
apps/infrastructure/src/modules/website/iam_role.tf

Added permissions to write, delete and query the subscription dynamodb to host authenticated users role
Host authenticated users role didn't have permissions on the webinar subscriptions dynamodb, hence they could not subscribe to webinars.

[EC-310] -  host authenticated user now can subscribe to webinar

---

apps/infrastructure/src/modules/website/cloudfront.tf

Allowed https://*.dev.developer.pagopa.it in dev environment's csp
Allowed https://*.developer.pagopa.it in prod environment's csp
The chatbot UI could not reach the backend APIs with the following error:
`Refused to connect to 'https://api.chatbot.dev.developer.pagopa.it/queries' because it violates the following Content Security Policy directive: "connect-src 'self' https://cognito-identity.eu-south-1.amazonaws.com/ https://dynamodb.eu-south-1.amazonaws.com/ https://cognito-idp.eu-south-1.amazonaws.com/ https://raw.githubusercontent.com/pagopa/ https://raw.githubusercontent.com/teamdigitale/ https://*.cookielaw.org https://*.onetrust.com https://www.google-analytics.com/ https://api.io.italia.it/ *.google-analytics.com https://pagopa.matomo.cloud/".`

fix: allowing csp for intra domain communication

---

.changeset/cyan-dolls-reply.md
apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts

Move env variable in function
Move env variable in function

Move env variable in function

---

apps/infrastructure/src/modules/cms/ecs.tf

[DEV-2049] Fix ac env vars in strapi container

---

.changeset/nervous-wolves-confess.md
apps/nextjs-website/src/app/[productSlug]/tutorials/page.tsx
apps/nextjs-website/src/components/atoms/GuideMenu/GuideMenu.tsx
apps/nextjs-website/src/components/molecules/GuideCard/GuideCard.tsx
apps/nextjs-website/src/components/organisms/PostIntegration/PostIntegration.tsx
apps/nextjs-website/src/editorialComponents/Newsroom/Newsroom.tsx
apps/nextjs-website/src/helpers/breadcrumbs.helpers.ts
apps/nextjs-website/src/lib/strapi/makeProps/makeGuideListPages.ts
apps/nextjs-website/src/lib/strapi/makeProps/makeOverviews.ts

Add the `translate` attribute to manually determine whether a string should be translated or not
The warnings made unreadable the console during build process
Manually

[DEV-2116] Remove NextIntl warnings

---

.changeset/honest-donkeys-warn.md
apps/nextjs-website/src/app/profile/agreements/page.tsx
apps/nextjs-website/src/app/profile/chatbot-history/page.tsx
apps/nextjs-website/src/app/profile/personal-data/page.tsx

Some pages were missing the title
on localhost

[CAI-303] fix personal page titles 

---

.changeset/spicy-frogs-kick.md
packages/active-campaign-client/package.json
packages/active-campaign-client/src/scripts/alignUsersCompanyFields.ts

Fix deprecated user's company type field
Fix deprecated user's company type field
Manually

[DEV-2038] Add align users company field script

---

.changeset/twelve-avocados-marry.md
apps/chatbot/src/modules/chatbot.py
apps/chatbot/src/modules/vector_database.py

The url was hardcoded, now chatbot uses the env var.

[CAI-299] Chatbot/fix website url and html2md converter

---

.changeset/olive-eggs-wait.md
apps/infrastructure/src/modules/docs_redirect/cloudfront.tf
apps/infrastructure/src/modules/website/cloudfront.tf

Set minimum tls version to 1.2

---

.changeset/cuddly-spiders-sleep.md
apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts

Fix webinar slug validation to prevent editors from emptying the field

[DEV-2282] Fix webinar slug validation to prevent editors from emptying the field

---

.changeset/tidy-geckos-protect.md
apps/chatbot/src/modules/chatbot.py

Fix the bug where Presidio mask PII in Langfuse. It was running twice for the output.
have consintency between what is written in the DeveloperPortal chathistory and Langfuse.
Locally

[CAI-415] - Bug Fix of Presidio in Langfuse

---

.changeset/odd-dragons-mix.md
apps/nextjs-website/src/lib/api.ts
apps/nextjs-website/src/lib/cmsApi.ts

add logs for guide pages
logs are needed for performance measurement

[DEV-2350] Add logs in guide pages

---

.changeset/solid-dolls-trade.md
apps/nextjs-website/src/app/privacy-policy/page.tsx
apps/nextjs-website/src/app/terms-of-service/page.tsx

Add content wrapper to Privacy Policy and Terms of Service pages
The content wrapper adds a div with the "chatbot-page-content" id, needed for indicization
Localhost

[CAI-508] Add content wrapper to Privacy Policy and Terms of Service pages

---

.changeset/free-chefs-stay.md
apps/nextjs-website/src/components/molecules/BlocksRendererClient/BlocksRendererClient.tsx
apps/nextjs-website/src/components/molecules/CodeBlockPart/CodeBlockPart.tsx

BlocksRendererClient.tsx:
- Moved code block handling from modifiers to blocks to prevent HTML hydration errors (`<pre> inside <p>`)
- Added robust type checking and data extraction for code content
- Handle string, ReactElement, and array cases safely
- Added fallback to empty string if extraction fails
- Added simple inline `<code>` element in modifiers for text formatting
CodeBlockPart.tsx:
- Added defensive coding with safeCode variable to ensure string type
- Applied safeCode to both SyntaxHighlighter component and CopyToClipboard
- Prevents runtime errors when non-string values are passed

[DEV-2605]  Fixed SyntaxHighlighter "split is not a function" error by improving data handling in code blocks

---

.changeset/giant-pets-type.md
packages/gitbook-docs/src/scripts/generateGuidesMetadata.ts
packages/gitbook-docs/src/scripts/generateReleaseNotesMetadata.ts
packages/gitbook-docs/src/scripts/generateSolutionsMetadata.ts
packages/gitbook-docs/src/syncedResponses.ts

- Generate synced solution and synced solution list pages
- Generate synced release-notes
Manage sync FE with data coming from gitbook avoding to re-deploy
Manually

[DEV-2818] Update script to add synced data in s3
