pagopa/developer-portal

- .github/workflows/deploy-website.yaml
- .github/workflows/infra-ci.yml
- .github/workflows/infra-deploy.yml
- .infrastructure/README.md
- .infrastructure/env/prod/backend.tfvars
- .infrastructure/env/prod/terraform.tfvars
Initialize the resources required to create the production environment using terraform.
- Add terraform variables for production
- Add backend variables for production
- Update GitHub Actions workflows
> Init prod environment resources

- .infrastructure/10_dns.tf
- .infrastructure/98_variables.tf
- .infrastructure/env/dev/terraform.tfvars
- .infrastructure/env/prod/terraform.tfvars
> Add dns delegate records

- .infrastructure/10_dns.tf
- .infrastructure/11_certs.tf
Link the CDN domain with a custom domain, so the website is served accessing to the custom domain.
- Move DNS record under proper file
- Link CDN to custom domain
We need to access the website with a custom domain
> Link cdn to custom domain

- .infrastructure/10_dns.tf
- .infrastructure/60_cdn.tf
> [DEV-379] - DNS aliases

- .github/actions/deploy/action.yaml
- .github/workflows/deploy-website.yaml
Enable the CD on dev environment when a PR is merged.
- Create a new deploy action
- Change the action that deploys the website to call the composite action
- Add trigger on PR
We want to deploy on the AWS S3 bucket any new changes made when a PR has been closed and merged to `main`.
> [DEV-678] - Automatic deploy on DEV environment

- .github/labeler.yaml
- .github/workflows/labeler.yaml
We want to add some labels to the PR's so we can easily see what the changes are about.
> Automatically add labels to PR

- apps/nextjs-website/src/_contents/translations.ts
> Fix instagram link

- .github/workflows/labeler.yaml
Improve workflow that add labels including PR size label
Add size label to the PR
We'd like to keep track of the size of each PR, so we can improve our quality
> Add PR size label

- .github/auto-assign.yaml
- .github/workflows/assign-pr.yaml
When someone opens a PR, it will be automatically set as Assignee
> Create workflow to auto assign PR

- .infrastructure/identity/main.tf
Without the PR the deploy fails because of [update on oidc integration with aws](https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/).
> Update github OIDC thumbprint

- .infrastructure/60_cdn.tf
Add URL to CSP
We need to get some OpenAPI from GitHub
> [DEV-703] - Add https://raw.githubusercontent.com/pagopa/ to security policy

- .infrastructure/60_cdn.tf
Allow to get images to https://io.italia.it/assets/
The App IO OpenAPI shows the IO icon and gets it from https://io.italia.it/assets
Manually
> [DEV-705] - Add https://io.italia.it/assets/ to img-src in CSP

- apps/nextjs-website/src/_contents/appIo/appIO.ts
Fix order of tabs for App IO header.
According to Figma, order should be:
- Panoramica
- Quick Start
- API
- Tutorial
- Guide e Manuali
> [DEV-707] - Fix order of App IO subpaths

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/pages/index.tsx
depends on: #115 
add documentation links to homepage
add documentation links to homepage
User can see documentation links component in homepage (http://localhost:3000/)
> [DEV-710] - Feature homepage/add links

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/organisms/News/News.tsx
- apps/nextjs-website/src/components/organisms/TutorialsOverview/TutorialsOverview.tsx
- apps/nextjs-website/src/pages/[productSlug]/overview.tsx
- apps/nextjs-website/src/pages/index.tsx
depends on: #115 
add news section to homepage
add news section to homepage
User can see news section component in homepage (http://localhost:3000/)
TODO: components and contents of new are work in progress
> [DEV-711] - Feature homepage/add news section

- apps/nextjs-website/src/_contents/appIo/appIO.ts
- apps/nextjs-website/src/_contents/appIo/guideLists.ts
- apps/nextjs-website/src/_contents/appIo/guideListsPath.ts
- apps/nextjs-website/src/_contents/products.ts
Add guides references to the index page of App IO's guides.
Note: we know the icon of the `Supporto agli Enti` is not correct. Icon is not ready at the moment, we are going to change it later.
> [DEV-699] - Add App IO guide index page

- .github/actions/deploy/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/deploy-website.yaml
- .gitignore
- README.md
- apps/nextjs-website/.env.default
- apps/nextjs-website/package.json
- apps/nextjs-website/scripts/fetch-docs.sh
- apps/nextjs-website/src/config.ts
- package-lock.json
- packages/gitbook-docs/.eslintrc.json
- packages/gitbook-docs/jest.config.ts
- packages/gitbook-docs/package.json
- packages/gitbook-docs/src/parseDoc.ts
- packages/gitbook-docs/tsconfig.json
- Add gitbook-docs package
- Add script to download the gitbook contents
- Update workflows to download GitBook docs before build the site
- Add the environment containing the path to gitbook docs to `nextjs-website`
The system should fetch some contents from GitBook. This PR provide the fetch process and the utilities to read the contents coming from GitBook. 
Locally.
> Add gitbook-docs

- .github/actions/deploy/action.yaml
Add missing shell to deploy action
The [deploy action fails](https://github.com/pagopa/developer-portal/actions/runs/5464497578)
```
/home/runner/work/developer-portal/developer-portal/./.github/actions/deploy/action.yaml (Line: 37, Col: 7): Required property is missing: shell
```
> Add missing shell to deploy action

- apps/nextjs-website/src/_contents/ioSign/ioSign.ts
- apps/nextjs-website/src/_contents/ioSign/overview.ts
- apps/nextjs-website/src/_contents/ioSign/overviewPath.ts
- apps/nextjs-website/src/_contents/ioSign/tutorialPath.ts
- apps/nextjs-website/src/_contents/ioSign/tutorials.ts
- apps/nextjs-website/src/helpers/getIconFromName.tsx
Add contents for the IO-Sign Overview page
We want to show the information about IO Sign.
> [DEV-610] - Add IO-Sign Overview

- apps/nextjs-website/src/_contents/pagoPa/overview.ts
- apps/nextjs-website/src/_contents/pagoPa/pagoPa.ts
- apps/nextjs-website/src/_contents/pagoPa/tutorialPath.ts
- apps/nextjs-website/src/_contents/pagoPa/tutorials.ts
- apps/nextjs-website/src/helpers/getIconFromName.tsx
Add contents to the pagoPA overview page.
Note that some sections are missing, because we need to update the React components.
> [DEV-636] - Add pagoPA overview

- apps/nextjs-website/src/_contents/pagoPa/guideLists.ts
Fix contents of pagoPA guide index page
Changes made here have been tracked as [checklist in this activity](https://pagopa.atlassian.net/browse/DEV-700).
> Fix contents of pagoPA guide index page

- apps/nextjs-website/src/_contents/ioSign/guideLists.ts
Fix some contents of IO-sign guide index page
Changes made here have been tracked as [checklist in this activity](https://pagopa.atlassian.net/browse/DEV-702).
Also, other changes are tracked with cards [DEV-724](https://pagopa.atlassian.net/browse/DEV-724) and [DEV-725](https://pagopa.atlassian.net/browse/DEV-725)
[DEV-724]: https://pagopa.atlassian.net/browse/DEV-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-725]: https://pagopa.atlassian.net/browse/DEV-725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-724, DEV-725] - Fix some contents of IO-sign guide index page

- .github/actions/deploy/action.yaml
Add environment on export step
The deploy fails.
Manually
> Add environment to export step

- apps/cloudfront-functions/src/__tests__/viewer-request-handler.test.ts
- apps/cloudfront-functions/src/viewer-request-handler.ts
Visiting the following page `/io-sign/guides/manuale-operativo/v1.0` the cloudfront function did not add the `.html` suffix
Unit tests.
> DEV-729 Improve cloudfront function

- apps/nextjs-website/src/_contents/appIo/tutorials.ts
- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/atoms/LinkButton/LinkButton.tsx
- apps/nextjs-website/src/components/organisms/News/News.tsx
- apps/nextjs-website/src/components/organisms/TutorialsOverview/TutorialsOverview.tsx
- apps/nextjs-website/src/editorialComponents/Newsroom/Newsroom.tsx
- apps/nextjs-website/src/lib/types/tutorialData.ts
- Refactor add custom newsroom component
- add disable to LinkButton
- manage coomingsoon newsroom
Update newsroom component
User can see updated newsroom component in http://localhost:3000/app-io/overview
> Fix newsroom component

- apps/nextjs-website/src/_contents/appIo/overview.ts
- apps/nextjs-website/src/_contents/ioSign/overview.ts
- apps/nextjs-website/src/_contents/pagoPa/overview.ts
- apps/nextjs-website/src/_contents/send/overview.ts
- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/organisms/StartInfo/StartInfo.tsx
- apps/nextjs-website/src/pages/[productSlug]/overview.tsx
Fix start info cta customizable by product
Fix start info cta customizable by product
user can see start info component on: http://localhost:3000/app-io/overview
> [DEV-736] - fix start info cta

- apps/nextjs-website/src/editorialComponents/Newsroom/Newsroom.tsx
Set image rounded corner in newsroom items component
Rounded corners with CSS 
Manually
> Set image rounded corner in newsroom items component

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/pages/terms-of-service.tsx
> DEV-743 Add terms of service

- apps/nextjs-website/src/_contents/translations.ts
Remove unused link from footer
We don't want any links that do not point somewhere.
Locally
> Remove link from footer

- apps/nextjs-website/package.json
- apps/nextjs-website/scripts/fetch-docs.sh
- apps/nextjs-website/src/_contents/appIo/guideLists.ts
- apps/nextjs-website/src/_contents/appIo/guides.ts
- apps/nextjs-website/src/_contents/appIo/overview.ts
- apps/nextjs-website/src/_contents/send/guideLists.ts
- apps/nextjs-website/src/_contents/send/guides.ts
- apps/nextjs-website/src/_contents/send/overview.ts
- Update fetch-docs script
- Add missing docs
- Update references
Some guides were missing.
Locally
> Update gitbook docs

- .github/actions/deploy/action.yaml
Enable caching for NextJS build
Add step that caches NextJS build files
We want to improve performances of builds
> Add NextJS build cache

- apps/nextjs-website/src/_contents/appIo/tutorialLists.ts
- apps/nextjs-website/src/_contents/ioSign/tutorialLists.ts
- apps/nextjs-website/src/_contents/send/tutorialLists.ts
The copy of the tutorial index pages is wrong.
Fix copy
> [DEV-784] - Fix copy on tutorial index pages

- packages/gitbook-docs/src/renderContent.ts
Add as comment al the components we are going to implement this sprint
> Add missing components to implement

- apps/nextjs-website/src/components/organisms/GuideContent/GuideContent.tsx
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/item.ts
- packages/gitbook-docs/src/markdoc/schema/list.ts
- packages/gitbook-docs/src/parseContent.ts
- packages/gitbook-docs/src/renderContent.ts
- Add new schemas (`list` and `item`)
- Change `RenderingComponents`
Add the parsing for kind of gitbook list
Unit Test.
> DEV-800 Add gitbook list parsing

- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/parseContent.ts
depends on #185 
- Add regex to translate any html anchor to a valid Markdoc tag.
- Ignore rendering of tag anchor
In some pages the html anchor is rendered as string (e.g. `<a href="#id" id="id"></a>`)
Unit tests
> DEV-758 Fix gitbook title render

- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/parseContent.ts
- Add regex to convert html tag `<p>` to Markdoc tag.
The system must ignore any `<p>` html tag.
Unit test
> DEV-813 Ignore any <p> tag

- apps/nextjs-website/src/components/organisms/GuideContent/GuideContent.tsx
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/styledText.ts
- packages/gitbook-docs/src/parseContent.ts
- packages/gitbook-docs/src/renderContent.ts
Add styled text parsing.
The system should render styled text
Unit tests.
> DEV-808 Parse styled text

- apps/nextjs-website/src/components/organisms/GuideContent/GuideContent.tsx
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/tab.ts
- packages/gitbook-docs/src/markdoc/schema/tabs.ts
- packages/gitbook-docs/src/parseContent.ts
- packages/gitbook-docs/src/renderContent.ts
- Add new `tabs` and `tab` schemas
- Change `RenderingComponents`
Add the parsing for kind of gitbook tabs blocks
Unit Test
> [DEV-806] - Add GitBook tabs and tab parsing

- apps/nextjs-website/src/components/organisms/GuideContent/GuideContent.tsx
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/errors.ts
- packages/gitbook-docs/src/markdoc/schema/embed.ts
- packages/gitbook-docs/src/markdoc/schema/file.ts
- packages/gitbook-docs/src/parseContent.ts
- packages/gitbook-docs/src/renderContent.ts
- Add new `embed` schema
- Change `RenderingComponents`
Add the parsing for kind of gitbook embed blocks
Unit Test
> [DEV-804] - Add GitBook embed parsing

- apps/nextjs-website/src/components/organisms/GuideContent/GuideContent.tsx
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/details.ts
- packages/gitbook-docs/src/parseContent.ts
- packages/gitbook-docs/src/renderContent.ts
- Add schema to parse expandable
- Add unit test
- Add renders props
The system must parse without error expandable sections from gitbook
Unit tests
> DEV-807 Add expandable parser

- apps/nextjs-website/src/components/organisms/GuideContent/GuideContent.tsx
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/table.ts
- packages/gitbook-docs/src/parseContent.ts
- packages/gitbook-docs/src/renderContent.ts
- Add Table schema
- Override renders elements
- Add new props to content render
The system must parse gitbook tables without errors.
Unit test and local test
> DEV-805 Add table parser

- package-lock.json
- packages/gitbook-docs/package.json
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/document.ts
- packages/gitbook-docs/src/parseContent.ts
- Install js-yaml
- Add document schema
- Add tests
Some pages has the description on frontmatter. The system should extract it and place it as paragraph into the page
Unit tests.
> DEV-822 Add description parser

- apps/nextjs-website/src/_contents/appIo/overview.ts
- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/atoms/CopyToClipboard/CopyToClipboard.tsx
- apps/nextjs-website/src/components/molecules/CodeBlockPart/CodeBlockPart.tsx
- remove cooming soon
- fix mobile ui
- update copy to clipboard button
Align quickstart page to mock
User can see updated page on: http://localhost:3000/app-io/quick-start
> [DEV-827, DEV-826] Fix/quick start page

- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/heading.ts
- packages/gitbook-docs/src/markdoc/schema/sanitizedText.ts
- packages/gitbook-docs/src/parseMenu.ts
- Parse heading text as sanitizedText
We don't want any emojis in h1 heading
Unit test
> [DEV-834] - Remove emoji from heading

- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/parseContent.ts
Add node image parser
The native markdown image didn't work as expected.
Unit test.
> DEV-838 Parse native markdown images

- apps/nextjs-website/src/components/atoms/CopyToClipboard/CopyToClipboard.tsx
- apps/nextjs-website/src/components/molecules/CodeBlockPart/CodeBlockPart.tsx
- apps/nextjs-website/src/components/organisms/ApiTesterPart/ApiTesterPart.tsx
- fix copy to clipboard animation
- add fixed width to api tester menu
- wrap text inside code block
UI fixes of api io quick start page
User can see updated UI on:  http://localhost:3000/app-io/quick-start
[Screencast from 28-07-2023 10:39:53.webm](https://github.com/pagopa/developer-portal/assets/24475319/b8397feb-d44b-4dcd-99d8-7c07db3eab16)
> [DEV-840 DEV-825] - Quick start/fix code block

- apps/nextjs-website/src/components/organisms/GitBookContent/GitBookContent.tsx
- apps/nextjs-website/src/components/organisms/GitBookContent/components/PageLink.tsx
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/pageLink.ts
- packages/gitbook-docs/src/parseContent.ts
- packages/gitbook-docs/src/renderContent.ts
- Create parser for content-ref element
- Create PageLink component
- Render PageLink
> [DEV-835] - Content-ref parser

- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/details.ts
- Improve a test about expandable
- Add missing tags to parse config
The tags inside a `<details>` tag are not parsed.
Unit test and locally.
> DEV-839 Fix expandable children rendering

- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/details.ts
Reverts pagopa/developer-portal#219
> Revert "DEV-839 Fix expandable children rendering"

- apps/nextjs-website/src/_contents/translations.ts
> [DEV-779] - Add PNRR link to footer

- apps/nextjs-website/src/components/organisms/ApiTesterPart/ApiTesterPart.tsx
Fix api tester width
Fix api tester width
User can see api tester on: http://localhost:3000/app-io/quick-start
> Fix Api tester

- package-lock.json
- package.json
Upgrade turbo to last version
On macbook pro m1 pro running `npm run dev` does not work because of incompatibilities of turbo, upgrading it to the last version solves the problem
run `npm run dev` with current version giving error. 
`npm run dev`  with last version works
> upgrade turbo

- .github/actions/build-nextjs-website/action.yaml
- .github/actions/deploy/action.yaml
- .github/actions/upload-nextjs-bundle-stats/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/nextjs_bundle_analysis.yml
This PR is required to verify if the Action that compute the NextJS bundle size works
> Refactor on GitHub actions

- package-lock.json
- packages/gitbook-docs/package.json
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/schema/htmltable.ts
- packages/gitbook-docs/src/markdoc/tokenProcessor.ts
- packages/gitbook-docs/src/parseContent.ts
- Add html parser
The system must parse gitbook html table without errors.
Unit test and local test.
> Parse gitbook html table

- packages/gitbook-docs/src/__tests__/parseInPageMenu.test.ts
- packages/gitbook-docs/src/parseContent.ts
- packages/gitbook-docs/src/renderContent.ts
Parse the in-page menu.
- Add new parser `parseInPageMenu`.
The system must render the in-page menu which is composed by all `heading` nodes.
Unit test.
> Add in-page menu parser

- apps/nextjs-website/src/components/organisms/GitBookContent/components/CodeBlock.tsx
- apps/nextjs-website/src/components/organisms/GitBookContent/components/Item.tsx
- apps/nextjs-website/src/pages/[productSlug]/guides/[...productGuidePage].tsx
- apps/nextjs-website/src/pages/[productSlug]/tutorials/[...productTutorialPage].tsx
Add word break to render gitbook components
Fix mobile visualization of tutorial
User see tutorial render correctly from mobile visualization on: http://localhost:3000/send/tutorials/come-inserire-una-notifica-via-curl
> [DEV-751] - Fix mobile style for tutorial and guide pages

- .github/workflows/stale.yaml
Decrease time to set PR as stale to 14 days.
Increase time to close PR if stale to 21 days.
> Decrease time to set PR as stale

- README.md
> Remove CI badge from README

- apps/nextjs-website/src/components/organisms/GitBookContent/components/Image.tsx
Remove horizontal padding around images in Guides and Manuals section 
The padding was wrong
Manually
From this:
To this:
> [DEV-889] Fix Image layout by removing unwanted padding

- apps/nextjs-website/src/_contents/appIo/tutorialLists.ts
- apps/nextjs-website/src/_contents/ioSign/tutorialLists.ts
- apps/nextjs-website/src/_contents/pagoPa/tutorialLists.ts
- apps/nextjs-website/src/_contents/send/tutorialLists.ts
- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/organisms/News/News.tsx
- apps/nextjs-website/src/editorialComponents/Newsroom/Newsroom.tsx
- apps/nextjs-website/src/lib/types/tutorialData.ts
- apps/nextjs-website/src/pages/[productSlug]/tutorials.tsx
Set date property as optional in Newsroom and news editorial components and temporary remove tutorial dates from static contents
Remove tutorial dates from static contents
The date source has not yet been agreed
Manually
> [DEV-883] Remove tutorial dates from static contents

- apps/nextjs-website/src/_contents/pagoPa/pagoPa.ts
- apps/nextjs-website/src/_contents/pagoPa/quickStartGuide.ts
- apps/nextjs-website/src/_contents/pagoPa/quickStartGuidePath.ts
- apps/nextjs-website/src/_contents/products.ts
Add quick start page for PagoPA
Add quick start page for PagoPA
User can see PagoPA quick start page on: http://localhost:3000/pago-pa/quick-start.
> [DEV-753] - add pago pa quick start page

- .github/actions/branch-up-to-date/action.yaml
- .github/workflows/check_branch_update.yaml
Add a workflow that verifies the branch is up to date with base branch.
- Create new GitHub Action that verifies branch is up to date with base branch
We want to make sure our branch is up to date with base branch.
> [DEV-918] Verify branch is up to date when opening a PR

- .github/actions/link-pr-to-jira-activity/action.yaml
- .github/workflows/check_pr_title.yaml
Drop a message if the PR hasn't been linked to a Jira activity.
- Add new GitHub action that comments if the title doesn't contain the Jira Activity's id
We want to link a PR to a Jira activity.
> [DEV-919] Verify PR has a link to Jira activity

- apps/nextjs-website/src/components/atoms/TypographyPart/TypographyPart.tsx
Remove break-all style from paragraphs in quick-start pages
break-all cuts words in two
Manually
> [DEV-853] - Remove break-all style from paragraphs in quick-start pages

- apps/nextjs-website/src/_contents/pagoPa/overview.ts
- apps/nextjs-website/src/_contents/translations.ts
Add pagoPA's quick start links to home page and overview page
The links were disabled
Manually
> [DEV-925] - Add pagoPa quick start links to home page and to pagoPA overview

- apps/nextjs-website/src/_contents/send/api.ts
- apps/nextjs-website/src/_contents/send/apiPath.ts
- apps/nextjs-website/src/_contents/send/overview.ts
Add different links to Send API using 'spec' query param
The same link was appearing twice. With 'spec' query param is now possible to distinguish between the two API
Manually
> [DEV-738] - Add different links to Send API using 'spec' query param

- apps/nextjs-website/src/_contents/send/quickStartGuide.ts
> [DEV-932] - Replace href Link- Selfcare

- CODEOWNERS
- Add developers as codeowners to frontend folders
We want to delegate the approval of Fronend specific changes to others.
> [DEV-920] Update CODEOWNERS

- apps/nextjs-website/src/_contents/pagoPa/bannerLinks.ts
> [DPC-52] Update "Self Care" in "Area Riservata"

- apps/nextjs-website/src/_contents/ioSign/overview.ts
> [DPC-59] - Update overview.ts

- apps/nextjs-website/src/editorialComponents/Footer/components/FooterColumn.tsx
Fix footer link to privacy policy and terms of service
Redirect to privacy policy and terms of service not working properly
Using Footer link to visit privacy policy and terms of service show pages correctly
> use anchor instead of Link

- apps/nextjs-website/package.json
> [DEV-942] docs hash update

- apps/nextjs-website/src/_contents/pagoPa/guides.ts
> [DEV-942] Update guides pagoPA

- apps/nextjs-website/src/_contents/appIo/guides.ts
> [DEV-942] Update guides AppIO

- apps/nextjs-website/src/_contents/appIo/guides.ts
- apps/nextjs-website/src/_contents/send/guides.ts
> [DEV-942] Update guides SEND

- apps/nextjs-website/src/_contents/appIo/guideLists.ts
- apps/nextjs-website/src/_contents/appIo/guides.ts
- apps/nextjs-website/src/_contents/appIo/overview.ts
- apps/nextjs-website/src/_contents/pagoPa/guideLists.ts
- apps/nextjs-website/src/_contents/pagoPa/guides.ts
- apps/nextjs-website/src/_contents/pagoPa/overview.ts
- apps/nextjs-website/src/_contents/send/guideLists.ts
- apps/nextjs-website/src/_contents/send/guides.ts
- apps/nextjs-website/src/_contents/send/overview.ts
> [DEV-946] Contents update - Link update

- apps/nextjs-website/src/_contents/pagoPa/quickStartGuide.ts
- apps/nextjs-website/src/_contents/send/guideLists.ts
- apps/nextjs-website/src/_contents/send/guides.ts
- apps/nextjs-website/src/_contents/send/overview.ts
> [DEV-947] Update version modello-integrazione

- apps/nextjs-website/package.json
> [DPC-58] update hash fetch-docs

- package-lock.json
- packages/eslint-config/eslint-recommended.js
- packages/eslint-config/eslint-strict.js
- packages/eslint-config/eslint-strong.js
- packages/eslint-config/package.json
- Install pagopa eslint rules
- Add new strict rules on eslint-config package
We have to be conform to the rules of company
N/A
> [DEV-952] Add eslint strict config

- apps/strapi-cms/.eslintrc.json
- apps/strapi-cms/config/admin.ts
- apps/strapi-cms/config/database.ts
- apps/strapi-cms/config/server.ts
- apps/strapi-cms/package.json
- apps/strapi-cms/src/admin/tsconfig.json
- apps/strapi-cms/src/index.ts
- apps/strapi-cms/tsconfig.json
- package-lock.json
- Improve tsconfig of `strapi-cms`
- Add eslint strong rules
- Change the `strapi-cms` code to be compliant with new rules
Add rules to enforce the code style
Yes, `npm run lint -w strapi-cms`
> Review add strapi PR

- .github/workflows/pr_enrich.yaml
We want to increase the limit of the check.
- Increase max_size to 800
> [DEV-954] Change PR size check max size

- CODEOWNERS
Update the path containing the website pages after the migration to the App router.
> [DEV-962] Update path with pages after migration to App Router

- apps/nextjs-website/package.json
> [DEV-942] update sync manual

- .infrastructure/11_certs.tf
According to the RFC for authentication, we need the new domain `auth.developer.pagopa.it`.
With this PR, we are going to create its TLS certificate.
- Create certificate for `auth.developer.pagopa.it`
> [DEV-968] Create TLS certificate for auth.developer.pagopa.it

- .infrastructure/10_dns.tf
Add DNS records for `auth.developer.pagopa.it`
> [DEV-972] Add CNAME records of auth.developer.pagopa.it

- .infrastructure/10_dns.tf
- .infrastructure/11_certs.tf
- .infrastructure/55_cognito.tf
Create user pool domain.
> **Note**
> The certificate `aws_acm_certificate.auth` has been already issued
- Create user pool domain
- Add DNS A record for user pool domain
> [DEV-970] Create user pool domain

- apps/nextjs-website/src/_contents/appIo/quickStartGuide.ts
- apps/nextjs-website/src/_contents/pagoPa/quickStartGuide.ts
> [DPC-60] change in curl string

- apps/nextjs-website/src/_contents/ioSign/quickStartGuide.ts
Changes requested by the team Firma con IO
Yes, locally
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
> [DPC-63] update quick start contents

- .infrastructure/10_dns.tf
- .infrastructure/55_cognito.tf
Create the user pool to allow the authentication through Cognito.
- Create user pool
- Create user pool app client
- Create user pool domain
- Use built-in functionality to send email
We need to store the information of created users somewhere to allow them to authenticate on the developer portal.
> [DEV-969] Create AWS Cognito resources

- apps/nextjs-website/src/_contents/send/api.ts
yes, locally
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
> [DPC-65] SEND update openapi url

- apps/nextjs-website/src/_contents/ioSign/quickStartGuide.ts
requested by Firma con IO Team
> [DPC-63] update quick start Firma con IO

- docs/architecture/decisions/0004-use-gitbook-client.md
- docs/architecture/decisions/0007-retrieve-gitbook-content-from-github-repository.md
- docs/how-to/add-a-new-gitbook-docs.md
- docs/how-to/update-gitbook-docs.md
- Add How-To section on `docs`.
- Add new ADR about GitBook content sync
> [DEV-941] - Add "how to" and ADR

- apps/nextjs-website/src/_contents/ioSign/quickStartGuide.ts
> [DPC-63] last modify quick start

- apps/nextjs-website/src/app/[productSlug]/guides/[...productGuidePage]/page.tsx
- apps/nextjs-website/src/components/atoms/GuideMenu/GuideMenu.tsx
- apps/nextjs-website/src/components/atoms/ProductHeader/ProductHeader.tsx
- apps/nextjs-website/src/components/atoms/ProductHeader/useScrollUp.ts
- apps/nextjs-website/src/components/molecules/SiteHeader/SiteHeader.tsx
- apps/nextjs-website/src/editorialComponents/Header/Header.tsx
Fix the sticky header regression after the layout refactor
The layout refactor divided the header into different components so it became necessary to find another solution in order to obtain the previous behaviour 
Manually
> [DEV-940] Sticky headers

- docs/how-to/add-a-new-gitbook-docs.md
- Update How-To section on `docs` about new guides.
> [DEV-987] - Add How To add a new guide

- apps/nextjs-website/package.json
- apps/nextjs-website/src/_contents/appIo/guideLists.ts
- apps/nextjs-website/src/_contents/appIo/guides.ts
- apps/nextjs-website/src/_contents/appIo/overview.ts
Update IO "Guida Tecnica" and  "Manuale Servizi", alignment also in internal links
Version update of 2 manuals
Locally
> [DPC-72] Update manuals IO App

- apps/nextjs-website/src/_contents/appIo/guideLists.ts
- apps/nextjs-website/src/_contents/appIo/guides.ts
Uncommented "Carta Giovani Nazionale" in Guides.ts because the space is now in sync.
> [DEV-904] Uncomment Carta Giovani in guides.ts

- apps/nextjs-website/src/_contents/appIo/overview.ts
> [DPC-73] link typo

- .github/workflows/deploy_website.yaml
> [DEV-992] - Fix Cognito environment variables

- apps/nextjs-website/src/_contents/send/api.ts
> [DPC-69] Update link API

- .infrastructure/55_cognito.tf
- apps/cognito-functions/package.json
- apps/cognito-functions/src/main.ts
- apps/cognito-functions/src/send-email-handler.ts
- apps/cognito-functions/tsconfig.json
We want an easy way to bundle more than one Lambda function and allow the execution in a simple way.
- Create second Lambda handler
- Bundle the handlers into a single file
Manually
> Handle multiple AWS Lambda functions

- apps/nextjs-website/package.json
> [DEV-899] Update Commit Sync Manuals

- apps/nextjs-website/src/_contents/send/bannerLinks.ts
bannerLinks file
Changed support request method
Locally
> [DPC-81] Update support link

- apps/nextjs-website/package.json
- apps/nextjs-website/src/_contents/send/guides.ts
Change the ref for sync to docs
> [DPC-91] Update version "Approfondimenti sull’integrazione" SEND

- apps/nextjs-website/package.json
> [DPC-85] Update images

- apps/nextjs-website/package.json
Fix the `start` command of `nextjs-website` application
The `start` command throwed an error.
> [DEV-1101] - Fix start command for nextjs-website

- apps/nextjs-website/src/app/auth/confirmation/page.tsx
Add confirmation page that evaluate username and code through congnito API after sign-up and confirm user if valid
Allow user confirmation through link in email 
Creating a new user and navigate on http://localhost:3000/auth/confirmation?username=XXX&code=YYY using instead of XXX and YYY username and code received in email if valid you should redirected to `/auth/account-activated` if invalid you should stay on confirmation route and see 404 error
[Screencast from 31-10-2023 18:26:52.webm](https://github.com/pagopa/developer-portal/assets/24475319/55f27233-ef3b-4688-9716-552d08cc0962)
> [DEV-1062] Add confirmation page

- apps/nextjs-website/src/_contents/appIo/overview.ts
> [DPC-93]Update subtitle

- apps/nextjs-website/package.json
> [DPC-86] Update Tutorial contents

- apps/nextjs-website/src/app/auth/sign-up/page.tsx
> Return PageNotFound on prod environment

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/app/webinars/[webinarSlug]/page.tsx
- apps/nextjs-website/src/components/organisms/SpeakerList/SpeakerList.tsx
Add speakers list component
Add speakers list component
User can see webinar detail page on: http://localhost:3000/webinars/comunicazioni-a-valore-legale
> [DEV-1070] add speakers component

- apps/nextjs-website/package.json
> [DPC-96] UPDATE docs

- apps/nextjs-website/package.json
- apps/nextjs-website/src/_contents/send/api.ts
> [DPC-69] change link to yaml

- apps/nextjs-website/src/_contents/appIo/overview.ts
> [DPC-72] Update Version "Guida Tecnica"

- .infrastructure/55_cognito.tf
- apps/cognito-functions/src/__tests__/define-auth-challenge-handler.test.ts
- apps/cognito-functions/src/define-auth-challenge-handler.ts
- apps/cognito-functions/src/main.ts
> [!IMPORTANT]  
> The lambda in not yet connected to the cognito trigger. This will be done later once the UI is ready
- Add `defineAuthChallengeHandler`
- Add terraform lambda resource
Thee login flow must have the MFA via email
Unit test
> [DEV-1092] Add define auth challenge handler

- .infrastructure/55_cognito.tf
- apps/cognito-functions/src/__tests__/verify-auth-challenge-handler.test.ts
- apps/cognito-functions/src/main.ts
- apps/cognito-functions/src/verify-auth-challenge-handler.ts
> [!IMPORTANT]  
> The lambda in not yet connected to the cognito trigger. This will be done later once the UI is ready
- Add `verifyAuthChallengeHandler`
- Add terraform lambda resource
Thee login flow must have the MFA via email. This PR add the logic to check the verification code provided by the user.
Unit test
> [DEV-1093] Add verify auth challenge handler

- .infrastructure/55_cognito.tf
- apps/cognito-functions/src/__tests__/create-auth-challenge-handler.test.ts
- apps/cognito-functions/src/create-auth-challenge-handler.ts
- apps/cognito-functions/src/main.ts
> [!IMPORTANT]  
> The lambda in not yet connected to the cognito trigger. This will be done later once the UI is ready
- Add `createAuthChallengeHandler`
- Add terraform lambda resource
Thee login flow must have the MFA via email. This PR add the logic to generate and send the verification code via email.
Unit test
> [DEV-1091] Add create auth challenge handler

- .infrastructure/55_cognito.tf
Remove useless `attach_policy_statements` from `cognito_define_auth_challenge` and `cognito_verify_auth_challenge` lambdas
The infra apply workflow raise an [error](https://github.com/pagopa/developer-portal/actions/runs/6876786296/job/18703094292#step:9:823)
```
│ Error: creating IAM Policy (cognito_define_auth_challenge-inline): MalformedPolicyDocument: Syntax errors in policy.
│ 	status code: 400, request id: 2de96ba9-8b15-4930-b3df-4fcaed571020
│ 
│   with module.cognito_define_auth_challenge_function.aws_iam_policy.additional_inline[0],
│   on .terraform/modules/cognito_define_auth_challenge_function/iam.tf line 386, in resource "aws_iam_policy" "additional_inline":
│  386: resource "aws_iam_policy" "additional_inline" {
│ 
╵
╷
│ Error: creating IAM Policy …
```
> Remove useless attach_policy_statements

- .infrastructure/55_cognito.tf
- Attach the cognito trigger to lambda functions that manages the auth flow
- Change cognito client auth_flow
The login must have email MFA flow
> [DEV-1118] Enable on cognito the custom auth for mfa

- apps/cognito-functions/esbuild.config.mjs
- apps/cognito-functions/package.json
Improve esbuild configuration using the `esbuild.config.mjs` file.
- Create `esbuild.config.mjs` file
- Add a workaround to allow the bundle generated to work (more details are available [here](https://github.com/mjmlio/mjml/issues/2132#issuecomment-1004713444))
We had an issue with the `uglify-js` dependency, imported by the `mjml` dependency.
Manually
> [DEV-1121] - Custom esbuild configuration

- apps/cognito-functions/src/__tests__/custom-message-handler.test.ts
- apps/cognito-functions/src/custom-message-handler.ts
- apps/cognito-functions/src/templates/confirmation-forgot-password.ts
- Handle CustomMessage_ForgotPassword event
- Add template for CustomMessage_ForgotPassword event
We want a custom email for "Forgot password?"
Partially with unit tests
> [DEV-1110] - Add forgot password email handler

- apps/cognito-functions/esbuild.config.mjs
- apps/cognito-functions/package.json
Use `esbuild` to bundle directly the `.ts` file, instead of producing the `.js` using `tsc` command.
- Remove `prebuild` script
- Change the entrypoint for `esbuild`
> [DEV-1121] Improve cognito-functions build

- apps/cognito-functions/src/__tests__/custom-message-handler.test.ts
- apps/cognito-functions/src/custom-message-handler.ts
Remove encodeURI function
That function encodes the required parameters `{` and `}`.
Manually
> [DEV-1124] Remove encodeURI

- apps/nextjs-website/src/_contents/send/quickStartGuide.ts
> [DPC-92] Update QuickStart SEND

- apps/nextjs-website/package.json
- apps/nextjs-website/src/_contents/pagoPa/guides.ts
- apps/nextjs-website/src/_contents/send/quickStartGuide.ts
Add manuals to import because they are linked in other manuals but should not be displayed in the manual list
> [DPC-88] Update pagoPA manuals

- apps/nextjs-website/src/_contents/send/quickStartGuide.ts
> [DPC-92] Typo error

- apps/nextjs-website/src/_contents/appIo/tutorialLists.ts
- apps/nextjs-website/src/_contents/ioSign/tutorialLists.ts
- apps/nextjs-website/src/_contents/pagoPa/tutorialLists.ts
- apps/nextjs-website/src/_contents/send/tutorialLists.ts
- apps/nextjs-website/src/app/[productSlug]/overview/page.tsx
- apps/nextjs-website/src/lib/types/tutorialData.ts
Add the showInOverview property to TutorialData to select Tutorials in overview pages
All the tutorials were visible in the overview pages. Now the tutorials can be selected and are limited to 3
Manually
> [DEV-1107] Select tutorials in overview pages

- apps/nextjs-website/package.json
- apps/nextjs-website/src/_contents/appIo/guides.ts
> [DPC-104] Added new manual App IO

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/organisms/Auth/SignUpForm.tsx
Add options to select company roles in signup form
Task DEV-1122
Step 1: go to `/auth/sign-up`
Step 2: click on `Tipologia Ente o Azienda`
> [DEV-1122] Add options to sign up form

- .github/workflows/deploy_website.yaml
Do not deploy website on production when merge is performed.
At the moment we decided not to deploy automatically on production environment.
> [DEV-1127] Remove prod as environment to perform deploy automatically

- .infrastructure/55_cognito.tf
- Add `user_preferences` attribute
We want to persist the user preferences
> [DEV-1132] Add user preferences attribute

- apps/nextjs-website/src/app/auth/confirmation/page.tsx
- apps/nextjs-website/src/app/auth/login/page.tsx
- apps/nextjs-website/src/app/auth/password-reset/page.tsx
- apps/nextjs-website/src/app/auth/sign-up/page.tsx
Show the authentication pages.
- Show the sign up page
- Show the login page
- Show the forgot password page
- Show the account activated page
> Show auth pages on production

- apps/nextjs-website/src/app/profile/personal-data/page.tsx
- apps/nextjs-website/src/components/atoms/InfoCardEditButton/InfoCardEditButton.tsx
- apps/nextjs-website/src/components/atoms/InfoCardItem/InfoCardItem.tsx
- apps/nextjs-website/src/components/atoms/UserInfo/UserInfo.tsx
- apps/nextjs-website/src/components/molecules/InfoCard/InfoCard.tsx
- apps/nextjs-website/src/helpers/user.helper.ts
- apps/nextjs-website/src/messages/it.json
Add personal data page
Logged user can see registration's personal information
After login user can naviagate on:  http://localhost:3000/profile/personal-data
> [DEV-1119] add profile personal data page

- .infrastructure/55_cognito.tf
Change from email address.
We want the email messages are coming from `Developer Portal <noreply@developer.pagopa.it>`.
> [DEV-1137] Change from email address value

- apps/nextjs-website/package.json
> [DPC-66] Update docs from gitbook

- apps/nextjs-website/src/_contents/appIo/quickStartGuide.ts
- apps/nextjs-website/src/_contents/pagoPa/quickStartGuide.ts
- apps/nextjs-website/src/_contents/send/quickStartGuide.ts
> [DPC-108] Replace Self Car with Area riservata

- apps/nextjs-website/src/app/profile/agreements/page.tsx
- apps/nextjs-website/src/helpers/user.helper.ts
- apps/nextjs-website/src/lib/types/auth.ts
- apps/nextjs-website/src/messages/it.json
Add newsletter subscribe/unsubscribe button to profile's agreements page
The authenticated user must be able to subscribe/unsubscribe from the newsletter by himself
Manually
> [DEV-1166] Add newsletter subscribe/unsubscribe button to profile's agreements page

- apps/nextjs-website/src/app/auth/change-password/page.tsx
- apps/nextjs-website/src/app/auth/password-reset/page.tsx
- apps/nextjs-website/src/app/auth/sign-up/page.tsx
- apps/nextjs-website/src/components/organisms/Auth/ConfirmSignUp.tsx
- apps/nextjs-website/src/components/organisms/Auth/SignUpForm.tsx
- apps/nextjs-website/src/lib/constants.ts
- apps/nextjs-website/src/lib/types/loader.ts
* Add a feedback when the user clicks on the resend email button
* Disable the sign up button after the first click
A feedback on the button click was needed
[x] Manually
https://github.com/pagopa/developer-portal/assets/146933303/240498b7-dbad-4f83-9cbd-82fadc1b90fa
> [DEV-1117]: Resend email feedback

- apps/nextjs-website/src/_contents/appIo/quickStartGuide.ts
> [DPC-107] update arcade link

- apps/cognito-functions/src/__tests__/custom-message-handler.test.ts
- apps/cognito-functions/src/custom-message-handler.ts
User that are already verified can request a new email with a verification link. This should not happen.
- Check user confirmation status before sending the verification email.
Unit tests
> [DEV-1139] Prevent verified user to receive a new verification email

- apps/cognito-functions/src/templates/post-confirmation-confirm-sign-up-message.ts
Add go to login button to confirmation signup email
Add go to login button to confirmation signup email
Manually
> [DEV-1143] update email button

- apps/nextjs-website/scripts/fetch-docs.sh
The script did not remove the `.tmp` folder correctly
> Fix cleanup phase on fetch-docs

- apps/nextjs-website/src/_contents/pagoPa/api.ts
> [DPC-111]Update url APi pagoPA

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/organisms/Auth/AccountActivatedCard.tsx
add redirect cta to login after signup
add redirect cta to login after signup
locally on: http://localhost:3000/auth/account-activated
> [DEV-1150] add redirect cta to login after signup

- apps/cognito-functions/src/__tests__/create-auth-challenge-handler.test.ts
- apps/cognito-functions/src/create-auth-challenge-handler.ts
- apps/cognito-functions/src/templates/otp-message.ts
- Update the email template for OTP message
- Update copy
We need to update accordingly to Figma design
Manually and unit tests
> [DEV-1173] Fix OTP email template and copy

- apps/nextjs-website/src/messages/it.json
Update copy
First draft of copy used English, now the copy is in Italian.
> [DEV-1174] Update copy of agreements page

- apps/nextjs-website/src/_contents/send/quickStartGuide.ts
> [DPC-92] review Quick start SEND

- apps/nextjs-website/src/_contents/webinars.ts
> [DPC-110] Changed slug for webinar

- apps/nextjs-website/src/_contents/send/tutorialLists.ts
> [DPC-101] Removed outdated tutorial

- apps/cognito-functions/src/__tests__/custom-message-handler.test.ts
- apps/cognito-functions/src/custom-message-handler.ts
If a registered (and confirmed) user requires a new email to verify the account, we raise an error.
- Update unit test
- Update implementation, returning an error
We don't want to send an email to the user in this scenario
Unit test and deploying a lambda manually
> [DEV-1175] Custom error if user is confirmed

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/app/auth/change-password/page.tsx
- apps/nextjs-website/src/app/auth/login/page.tsx
- apps/nextjs-website/src/app/auth/password-reset/page.tsx
- apps/nextjs-website/src/app/auth/sign-up/page.tsx
- apps/nextjs-website/src/components/molecules/ResendEmail/ResendEmail.tsx
- apps/nextjs-website/src/components/organisms/Auth/ConfirmLogin.tsx
- apps/nextjs-website/src/components/organisms/Auth/ConfirmSignUp.tsx
- apps/nextjs-website/src/config.ts
- apps/nextjs-website/src/lib/constants.ts
- apps/nextjs-website/src/messages/it.json
Fix copy of the ConfirmLogin component and move to a dedicated component resendEmail link
The copy were not aligned to design in Figma
Manually
> [DEV-1181] Fix confirm login copy

- apps/nextjs-website/src/components/atoms/UserInfo/UserInfo.tsx
- apps/nextjs-website/src/lib/api.ts
Getting ready for first release
- Remove some `isProduction` condition
> Remove isProduction filter

- apps/nextjs-website/src/app/privacy-policy/page.tsx
- apps/nextjs-website/src/app/terms-of-service/page.tsx
Add new versions of Privacy policy and Terms of service
Manually
> [DEV-1170, DEV-1171] Add new versions of Privacy policy and Terms of service

- apps/nextjs-website/src/_contents/webinars.ts
Fix webinar mobile view
Fix webinar mobile view
manually on: http://localhost:3000/webinars/nuove-api-io
> [DEV-1187] Fix webinar image from content

- apps/nextjs-website/src/components/atoms/UserInfo/UserInfo.tsx
- apps/nextjs-website/src/components/molecules/SiteHeader/SiteHeader.tsx
- apps/nextjs-website/src/editorialComponents/Footer/Footer.tsx
> [DEV-1188] Fix mobile site header layout

- apps/nextjs-website/src/_contents/translations.ts
> [DPC-117] changed link to SEND in footer

- .infrastructure/55_cognito.tf
Add `timeout` property to lambda functions
We faced some timeouts during the authentication.
> Add timeout to lambda functions

- apps/nextjs-website/src/components/organisms/GitBookContent/components/Item.tsx
Add style to list component so that it styles items correctly
DEV 1090
Go to `/pago-pa/guides/sanp/3.5.0/specifiche-attuative-del-nodo-dei-pagamenti-spc/funzionamento-generale/processi-di-pagamento` now the IO App logo should be next to APP IO label and not in the line below
> [DEV-1090] Fix inline images

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/app/profile/personal-data/page.tsx
- apps/nextjs-website/src/components/organisms/Auth/SignUpForm.tsx
* Add the translation to the role on the profile page
The role was displayed as the id
> [DEV-1151]: translate role on profile page

- apps/nextjs-website/package.json
> Release version

- apps/nextjs-website/package.json
Reverts pagopa/developer-portal#479
> Revert "Release version"

- apps/nextjs-website/package.json
- package-lock.json
> Release version 0.2.0

- apps/nextjs-website/package.json
> [DPC-102] New tutorial SEND sync

- apps/nextjs-website/src/_contents/webinars.ts
- apps/nextjs-website/src/app/profile/layout.tsx
- apps/nextjs-website/src/components/atoms/VimeoPlayer/VimeoPlayer.tsx
- apps/nextjs-website/src/components/molecules/WebinarPlayerSection/WebinarPlayerSection.tsx
- apps/nextjs-website/src/components/organisms/ProfileMenu/ProfileMenu.tsx
- apps/nextjs-website/src/components/organisms/WebinarDetailTemplate/WebinarDetailTemplate.tsx
- apps/nextjs-website/src/lib/types/webinar.ts
Depends on #497 
Add the webinar player section
The player was missing
Manually
> [DEV-1027, DEV-892] Webinar player section

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/app/page.tsx
- apps/nextjs-website/src/components/organisms/WebinarsSection/WebinarsSection.tsx
- apps/nextjs-website/src/messages/it.json
Set webinar section title on a date base
> [DEV-1221] Set webinar section title on a date base

- apps/nextjs-website/src/helpers/webinar.helpers.tsx
Set a different coming soon delta
> [DEV-1227] Set a different coming soon delta

- .infrastructure/55_cognito.tf
- .infrastructure/65_ses.tf
Pin version of Terraform modules.
We want to make sure to have pinned a Terraform modules, so we are sure to run the very same code every time.
> [DEV-1103] Pin version of terraform modules

- apps/nextjs-website/src/_contents/webinars.ts
Reverts pagopa/developer-portal#509
> Revert "[DEV-1224] Add hidden live webinar"

- .infrastructure/75_dashboard.tf
Create a simple dashboard with cognito information and lambda information
Locally
> [DEV-1237] Add simple main dashboard

- .infrastructure/75_dashboard.tf
Change region for CDN on dashboard
> [DEV-1237] Fix region of dashboard

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/organisms/Auth/SignUpForm.tsx
* Changed the sign up text regarding policy and terms of service
The text was missing the two links to the privacy policy and terms of service pages
> [DEV-1250]: update policy text with links

- .infrastructure/env/prod/terraform.tfvars
Remove the cdn custom header that prevents search engine to index
N/A
> [DEV-1275] Remove x-robots-tag custom header

- apps/nextjs-website/src/_contents/send/guideLists.ts
- apps/nextjs-website/src/_contents/send/guides.ts
- apps/nextjs-website/src/_contents/send/overview.ts
> [DPC-122] Update  version knowledge base SEND

- .infrastructure/60_cdn.tf
Refactor CSP to improve readability.
- Extract parts of CSP and put in separate variables
In this way is should be easier to make reviews and get where is the change.
Through the CI: the `terraform plan` should not show any changes in the CSP
> Refactor CSP parts to improve readability

- apps/nextjs-website/src/_contents/appIo/appIo.ts
> [DPC-115] Change in name "App IO"

- apps/nextjs-website/src/_contents/send/guides.ts
> [DPC-123] update list order for "Manuale Operativo"

- apps/nextjs-website/src/_contents/webinars.ts
- apps/nextjs-website/src/components/atoms/TimeSlot/TimeSlot.tsx
* Add UTC format to webinar's dates
* The missing UTC format caused some errors on the dates
> [DEV-1226]: fix timezone on webinars' dates

- apps/nextjs-website/package.json
- package-lock.json
> Release version 0.4.0

- apps/nextjs-website/package.json
- apps/nextjs-website/src/_contents/pagoPa/guideLists.ts
- apps/nextjs-website/src/_contents/pagoPa/guides.ts
- apps/nextjs-website/src/_contents/pagoPa/quickStartGuide.ts
> [DPC-119] Update version SACI & SANP

- CODEOWNERS
Update codeowners
Change ownership of frontend directories
> [DEV-1286] Update codeowners

- apps/nextjs-website/package.json
- package-lock.json
Bump version of nextjs-website
> Release version 0.4.1

- .changeset/honest-apricots-itch.md
- .changeset/tricky-ears-dance.md
- apps/nextjs-website/package.json
- apps/nextjs-website/src/_contents/appIo/guideLists.ts
- apps/nextjs-website/src/_contents/appIo/guides.ts
- apps/nextjs-website/src/_contents/appIo/overview.ts
- apps/nextjs-website/src/_contents/webinars.ts
> [DPC-125]Update version Guida tecnica

- .github/workflows/changelog.yaml
- package.json
> Move npm i to the script

- .infrastructure/55_cognito.tf
- .infrastructure/98_variables.tf
* Add `log_retention_days` variable
* Add `cloudwatch_logs_retention_in_days` to lambda definition
The logs need to be removed after a certain period of time.
> [DEV-1231] Add log_retention_days parameter to cloudwatch

- .changeset/thin-socks-relate.md
- apps/nextjs-website/src/editorialComponents/Newsroom/Newsroom.tsx
* Fix carousel mobile margin right
The carousel was missing the right margin on mobile
> [DEV-1242]: fix mobile carousel margin

- CODEOWNERS
Improve CODEOWNERS rules.
- Replace handles with group name
- Add rules to handle changesets files
> Improve CODEOWNERS file

- .changeset/eighty-toys-care.md
- apps/cloudfront-functions/src/__tests__/viewer-request-handler.test.ts
- apps/cloudfront-functions/src/viewer-request-handler.ts
Updated lambda checks to prevent `.woff2` font requests from being modified
This change is required to load fonts with `.woff2` format
> [DEV-1234] woff2 font format is not loaded

- .infrastructure/55_cognito.tf
Before this PR, a user that updates the email address is not able to perform a sign in nor with the original email address, nor with the new address (until the verification of the email address is complete).
> **When a user updates an attribute and your user pool verifies new attribute values**
They can sign in with the original attribute value before they have confirmed the code to verify the new value.
They can only sign in with the new attribute value after they have confirmed the code to verify the new value.
Reference: [AWS Documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html#user-pool-settings-verifications-verify-attribute-updates)
After this PR, a user can perform the login with the original email address, even …
> [DEV-1297] Enable attributes_require_verification_before_update on email address

- .changeset/shaggy-windows-swim.md
- apps/cognito-functions/src/__tests__/custom-message-handler.test.ts
- apps/cognito-functions/src/custom-message-handler.ts
- apps/cognito-functions/src/templates/confirmation-update-email-address.ts
Handle the event triggered when the user updates the email
- Create skelethon of email template
- Add new event to handle
Before this PR, when the user updates the email address, a verification code was sent to its new email address.
The behaviour we want is that the user receive a verification link.
Unit tests
> [DEV-1299] Handle user update attribute event in CognitoFunctions

- apps/nextjs-website/src/components/molecules/DesktopSiteHeader/DesktopSiteHeader.tsx
- apps/nextjs-website/src/components/molecules/MobileSiteHeader/MobileSiteHeader.tsx
Hide webinar link in production environment
The page is not yet ready to be published
> [DEV-1304] Hide webinar link in production environment

- apps/nextjs-website/src/app/[productSlug]/overview/page.tsx
- apps/nextjs-website/src/editorialComponents/Hero/Hero.tsx
Add a prop to Hero component to add the style that removes the overlap between the product's menu and the Hero
> [DEV-1306] Remove the overlap between the product's menu and the Hero

- .changeset/rude-kings-peel.md
- apps/nextjs-website/src/components/molecules/SubscribeToWebinar/SubscribeToWebinar.tsx
- apps/nextjs-website/src/components/molecules/WebinarCard/WebinarCard.tsx
Fix webinar show button
Webinar show button visible only in webinars and home pages
Webinar show button should only be visible in webinars and home pages not in detail page
Manually
> [DEV-1311] Fix webinar view button

- .infrastructure/50_storage.tf
Add Terraform resources for webinar questions
- Create DynamoDB table
We need a table to temporary contain the questions, so the hosts can answer them during the webinars
> [DEV-1077] Create DynamoDB table for webinar questions

- .infrastructure/55_cognito.tf
Depends on #575
Add resources to perform authorization for Cognito users
We need the hosts (of a webinar) to be able to read the questions that the attendees are making during a webinar.
> [DEV-1312] Create resources to authorize Cognito users

- .infrastructure/55_cognito.tf
The deploy infrastructure fails due to invalid role policy definition
> [DEV-1312] Fix cognito assume role policy

- .infrastructure/60_cdn.tf
- Add DynamoDB endpoint to CSP
- Add identity pool endpoint to CSP
We need to invoke the AWS services from the website
> [DEV-1313] Add identity pool and DynamoDB endpoints to CSP

- .infrastructure/10_dns.tf
Add TXT record to perform domain ownership verification
> [DEV-1276] Add TXT record due to domain ownership verification

- .github/actions/build-nextjs-website/action.yaml
- .github/actions/deploy/action.yaml
- .github/workflows/code_review.yaml
- .github/workflows/deploy_website.yaml
Add the environment to the deploy workflow
The systems needs new environment vars
> [DEV-1323] Update deploy workflow with new environments vars

- .changeset/selfish-bags-switch.md
- apps/nextjs-website/src/messages/it.json
Fix speakers and speakersTitle label in Webinar section
> [DEV-1327, DEV-1328] Fix speakers and speakersTitle label in Webinar section

- .changeset/good-oranges-visit.md
- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/components/organisms/Auth/ConfirmLogin.tsx
- apps/nextjs-website/src/components/organisms/Auth/ConfirmSignUp.tsx
Escape the html provided as route param so that no js can be injected. 
Go to `[/auth/sign-up?email=</strong><img src=1 onError="javascript:alert('XSS')">&step=CONFIRM_SIGN_UP](https://developer.pagopa.it/auth/sign-up?email=%3C/strong%3E%3Cimg%20src=1%20onError=%22javascript:alert(%27XSS%27)%22%3E&step=CONFIRM_SIGN_UP)`
check no popup will appear
> [DEV-1331] Fix xss issue

- .changeset/strange-peas-compare.md
- apps/nextjs-website/package.json
- apps/nextjs-website/src/_contents/pagoPa/guideLists.ts
- apps/nextjs-website/src/_contents/pagoPa/guides.ts
- apps/nextjs-website/src/_contents/pagoPa/quickStartGuide.ts
> [DPC-138] Update docs from gitbook

- .changeset/wicked-dots-attend.md
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/parseContent.ts
Remove old workaround and parses <p> tags as html.
Having the workaround caused %p to appear on tables
go to `pago-pa/guides/saci/3.1.0/specifiche-attuative-dei-codici-identificativi-di-versamento-riversamento-e-rendicontazione/flusso-di-rendicontazione`
> [DEV-1162] Remove workaround from parse content

- .changeset/nervous-ladybugs-sip.md
- .changeset/wicked-trainers-watch.md
- apps/nextjs-website/src/components/atoms/ApiViewer/ApiViewer.tsx
Show export button in StopLight Element's component of API pages
The team expressed the necessity to download the original yaml file
Manually
> [DPC-135] Show export button in StopLight Element's component of API pages

- .changeset/orange-colts-listen.md
- apps/nextjs-website/src/editorialComponents/Newsroom/Newsroom.tsx
- Refactor styles
Resizing the "Featured" section as the page loads (initially full screen)
Go to the home page and try reloading. You should not see full-screen images in the "Featured" section.
> [DEV-1238] Resizing the "Featured" section as the page loads

- .infrastructure/76_alarms.tf
- Create the alarm to monitor the Bounce rate
- Create the alarm to monitor the reputation complaint rate
- Create the alarm to monitor the daily sending quota
- Create the alarm to monitor the sending rate limit (which is, at the moment, 14/s)
We want to monitor if something went wrong with the SES service.
> [DEV-1291] Add alarms for SES

- .infrastructure/76_alarms.tf
- Create alarm to monitor Cognito SignUp throttled requests
- Create alarm to monitor Cognito SignIn throttled requests
- Create alarm to monitor Cognito TokenRefresh throttled requests
- Create alarms to monitor the Cognito Custom Message Lambda functions:
- Create the alarm to monitor the errors
- Create the alarm to monitor the throttles
- Create the alarm to monitor the duration
- Create the alarm to monitor the concurrent executions
- Create alarms to monitor the Cognito Post Confirmation Lambda functions:
- Create the alarm to monitor the errors
- Create the alarm to monitor the throttles
- Create the alarm to monitor the duration
- Create the alarm to monitor the concurrent executions
- Create alarms to monitor the Cognito Define Auth Challenge Lambda functions:
- Create the alarm …
> [DEV-1343] Add Cognito alarms

- .infrastructure/55_cognito.tf
Add `prevent_destroy` lifecycle to Cognito UserPool resource.
We want to secure the resource since it's a critical resource.
> [DEV-1290] Add prevent_destroy to Cognito UserPool

- .changeset/twenty-spoons-prove.md
- apps/nextjs-website/src/BuildConfig.ts
- apps/nextjs-website/src/BuildEnv.ts
- apps/nextjs-website/src/lib/strapi/StapiEnv.ts
- apps/nextjs-website/src/lib/strapi/StrapiConfig.ts
- apps/nextjs-website/src/lib/strapi/__tests__/fetchFromStrapi.test.ts
- apps/nextjs-website/src/lib/strapi/fetchFromStrapi.ts
- Create the BuildEnvironment
- Create the StrapiEnvironment
- Create the function to use to make API call to Strapi
We want to prepare the ground for future works that involve API call to Strapi.
With unit tests
> [DEV-1362] Add BuildEnv and Strapi utilities

- apps/nextjs-website/package.json
> [DEV-863] Changed broken link in gitbook

- .github/workflows/changelog.yaml
- package.json
- Add tag script in `package.json`
- Changeset now creates tags as well
> [DEV-1368] Instruct changeset action to create Git tags

- .github/workflows/changelog.yaml
- Changelog workflow now fetches also the tags
The workflow failed because tags created already existed.
> [DEV-1368] Fetch tags on repo checkout

- .changeset/proud-mirrors-think.md
- apps/nextjs-website/src/components/atoms/MobileUserInfo/MobileUserInfo.tsx
- apps/nextjs-website/src/components/molecules/MobileSiteHeader/MobileSiteHeader.tsx
> [DEV-1348] Close mobile menu on click

- .github/workflows/code_review.yaml
- .github/workflows/deploy_website.yaml
Make sure to build the static website on both environment, so the build workflow gets properly the environment variables set.
- Add missing env variable to a workflow
- Execute the build of the website on both environments (dev and prod)
Previous builds didn't get the environment variables, because no environment was set.
With this PR, we are going to run the build job on both environment, making sure the build job properly gets all the variables.
> [DEV-1387] Fix build workflow

- .github/workflows/changelog.yaml
The `fetch-tags` option in the `checkout` phase during the CI doesn't work as expected.
We need to add also the `fetch-depth` option, as suggested [in this comment](https://github.com/actions/checkout/issues/1471#issuecomment-1771231294) so then we are having the expected behaviour.
> [DEV-1387] Add fetch-depth option

- .infrastructure/10_dns.tf
- .infrastructure/98_variables.tf
- .infrastructure/env/dev/terraform.tfvars
- .infrastructure/env/prod/terraform.tfvars
Create DNS zone for CMS Strapi
Create DNS zone for CMS Strapi
Create DNS zone for CMS Strapi
> [DEV-1394] - Create DNS zone for CMS Strapi

- .github/workflows/deploy_infra.yml
- .github/workflows/deploy_website.yaml
Improve jobs' name to let it clear on what environment the workflow is executed.
We want to clearly see on what environment we are running the workflow.
> Improve jobs' name

- .changeset/gentle-bugs-beg.md
- apps/nextjs-website/package.json
- apps/nextjs-website/scripts/fetch-docs.sh
> [DEV-1375] Added branch for automatically Sync "docs/from-gitbook"

- .infrastructure/40_iam.tf
Create IAM Role ECS for CMS Strapi
Depends on #626 
Modify Terraform IAM file
Create IAM Role ECS for CMS Strapi
on AWS DGS Account
> [DEV-1386] - Create IAM Role ECS for CMS Strapi

- .infrastructure/10_dns.tf
- .infrastructure/11_certs.tf
- Remove DNS Zone not necessary
- Update SSL certificate options
We need to create the SSL certificate for the domain of the CMS
> [DEV-1382, DEV-1394] Fix SSL certificate for cms domain

- .infrastructure/55_cognito.tf
* Add `dynamodb:UpdateItem` permission to `devportal_authenticated_host_user`
The `devportal_authenticated_host_user` users should be able to update the questions on the database
> [DEV-1403]: add missing permission to devportal_authenticated_host_user

- .infrastructure/10_dns.tf
- .infrastructure/11_certs.tf
Reverts pagopa/developer-portal#652
> Revert "[DEV-1382, DEV-1394] Fix SSL certificate for cms domain"

- .infrastructure/11_certs.tf
Update CMS SSL certificate provider and zone id
- Change AWS Provider, using the global region
- Update zone id of the certificate
> [DEV-1382] Update CMS SSL certificate provider and zone id

- .infrastructure/10_dns.tf
Remove DNS hosted zone that is not used.
Depends on #659
> Remove useless DNS hosted zone

- .github/workflows/code_review.yaml
- .github/workflows/code_review_infra.yaml
- .github/workflows/deploy_website.yaml
Prevent the cancellation of any job if another one, in the matrix, fails.
> [DEV-1404] Add fail-fast option to avoid cancellation of a job if another one fails

- .changeset/little-boats-think.md
- apps/nextjs-website/src/editorialComponents/BannerLink/BannerLink.tsx
render html link
go to: /app-io/overview, check banner links
> [DEV-1402] update banner link

- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/messages/it.json
> [DPC-150] Correction of the sentence related to the pagoPA quickstart

- .infrastructure/41_iam_users.tf
- .infrastructure/42_iam_groups.tf
Create IAM user group (developers read only) and create IAM user for Mauro.
- Create a readonly group on AWS
- Create IAM user for Mauro
> [DEV-1400] Create developers readonly group and iam user

- .changeset/six-items-exist.md
- apps/cloudfront-functions/src/__tests__/viewer-request-handler.test.ts
- apps/cloudfront-functions/src/viewer-request-handler.ts
Reverts pagopa/developer-portal#679 due to a regression when visiting the homepage
> Revert "[DEV-1406] Handle the trailing slash of the URL"

- .infrastructure/certs.tf
Generate the SSL certificate to the Milan zone
The SSL certificate used by the load balancer must be in the same region of the load balancer.
> [DEV-1457] Change SSL certificate zone

- .infrastructure/dns.tf
Depends on #680
Add the domain validation options of the SSL certificate
> Add domain validation options to the set

- .changeset/moody-cats-bow.md
- apps/cloudfront-functions/src/__tests__/viewer-request-handler.test.ts
- apps/cloudfront-functions/src/viewer-request-handler.ts
- handle the trailing slash of the URL in cloudfront function
- add tests
On any developer portal page (excluding the home page), by adding a forward slash at the end of a path, e.g. https://developer.pagopa.it/app-io/guides/io-guida-tecnica → https://developer.pagopa.it/app-io/guides/io-guida-tecnica/ - causes a 404 error.
> [DEV-1406] Handle the trailing slash of the URL

- apps/strapi-cms/src/admin/tsconfig.json
- apps/strapi-cms/tsconfig.json
Due to an issue, we have to remove the `extends` within the Strapi's `tsconfig.json` files
> [DEV-1460] Remove extends within Strapi tsconfig.json files

- .infrastructure/ecs.tf
Setup by Terraform script one node active of ECS for deploy CMS STrapi
Setup by Terraform script one node active of ECS for deploy CMS STrapi
Setup by Terraform script one node active of ECS for deploy CMS STrapi
> [DEV-1461] - Terraform setup active one ECS node for CMS

- .infrastructure/.terraform.lock.hcl
- .infrastructure/cloudwatch_log_group.tf
- .infrastructure/ecs.tf
- .infrastructure/task-definitions/cms_app.json.tpl
Just a bunch of fixes related to Terraform files.
- Change log group name
- Change the desired count of ECS
- Update env variable names in task definition template
> Few fixes on Terraform files

- apps/nextjs-website/src/_contents/pagoPa/guideLists.ts
- apps/nextjs-website/src/_contents/pagoPa/guides.ts
- apps/nextjs-website/src/_contents/pagoPa/overview.ts
> [DPC-160] Change name 3.20 --> 3.2.1

- .github/workflows/deploy_cms.yaml
- Add continue-on-error: true
- Add the environment: ${{ inputs.environment }}
Without the `environment` the workflow fails due to missing secrets. Without the `continue-on-error: true` the workflow fails on re-run
N/A
> Update deploy cms workflow

- .github/workflows/deploy_website.yaml
- Add the `repository_dispatch` trigger
We want to deploy the new version of the website also from the CMS
> [DEV-1470] Add repository dispatch trigger

- .changeset/perfect-students-wash.md
- apps/nextjs-website/src/app/page.tsx
- apps/nextjs-website/src/lib/homepage.ts
- apps/nextjs-website/src/lib/strapi/homepage.ts
Fix product's description type by adding null type
The build was broken when the description field was empty
Manually
> [DEV-1471] Fix product's description type

- apps/nextjs-website/src/_contents/pagoPa/guides.ts
> [DPC-160] Fix pagoPA guides and manuals version

- apps/nextjs-website/src/_contents/pagoPa/guides.ts
Reverts pagopa/developer-portal#700
> Revert "[DPC-160] Fix pagoPA guides and manuals version"

- apps/nextjs-website/src/components/molecules/WebinarQuestion/WebinarQuestionRow.tsx
- apps/nextjs-website/src/components/organisms/WebinarQuestionsForm/WebinarQuestionsForm.tsx
- apps/nextjs-website/src/components/organisms/WebinarQuestionsTemplate/WebinarQuestionsTemplate.tsx
- apps/nextjs-website/src/lib/webinarApi.ts
- apps/nextjs-website/src/lib/webinars/__tests__/webinarQuestions.test.ts
- apps/nextjs-website/src/lib/webinars/dynamodb/__tests__/codec.test.ts
- apps/nextjs-website/src/lib/webinars/dynamodb/codec.ts
- apps/nextjs-website/src/lib/webinars/webinarQuestions.ts
- Update the structure of `WebinarQuestion`
- Update the structure of `WebinarQuestionUpdate`
- Add tests related to webinar question update
Increases the robustness of the solution and prevent type casting
Unit test and locally
> Webinar questions review

- .changeset/pretty-ears-work.md
- apps/nextjs-website/src/components/atoms/WebinarHeaderBanner/WebinarHeaderBanner.tsx
Fix banner visibility in homepage
Go to the homepage, check the banner is there,  
close it reload  
the banner should not be there  
go to local storage, delete the webinar key and reload the page  
now the banner should be visible again
> [DEV-1497] Fix homepage webinar banner visibility

- .github/actions/setup-terraform/action.yaml
- .github/workflows/code_review_infra.yaml
- .github/workflows/deploy_infra.yml
- apps/infrastructure/src/cloudfront.tf
GitHub workflows now reference the `apps/infrastructure` app.
We are migrating the infrastructure code into the monorepo
> [DEV-1430] Replace references of .infrastructure

- apps/nextjs-website/src/_contents/ioSign/quickStartGuide.ts
To avoid checking the version and use the "latest feature"
Manually, locally
> [DPC-171] Removes specific version and redirects to lates in Quick Start  Firma con IO

- apps/nextjs-website/src/_contents/ioSign/quickStartGuide.ts
Reverts pagopa/developer-portal#727
> Revert "[DPC-171] Removes specific version and redirects to lates in Quick Start  Firma con IO"

- apps/nextjs-website/src/_contents/pagoPa/guideLists.ts
- apps/nextjs-website/src/_contents/pagoPa/overview.ts
- apps/nextjs-website/src/_contents/pagoPa/quickStartGuide.ts
Reverts pagopa/developer-portal#726
> Revert "[DPC-175] Removes ref. to specific versions in the guide list and redirects to the latest pagoPA"

- .github/workflows/deploy_cms.yaml
- .github/workflows/deploy_website.yaml
- Add concurrency group in `deploy_website` workflow
- Add concurrency group in `deploy_cms` workflow
> [DEV-1448] Add concurrency group in deploy workflows

- .changeset/eight-cobras-argue.md
- apps/nextjs-website/src/_contents/webinars.ts
- apps/nextjs-website/src/app/webinars/page.tsx
- apps/nextjs-website/src/lib/api.ts
- apps/nextjs-website/src/lib/types/webinar.ts
This will add the possibility to add test webinar to the application, test webinars are not visible in homepage
and not visible in webinar index page, must be accessed by direct link
go to `webinars/always-live`, `webinars/test-2024-03-13` e `webinars/test-2024-03-14`
> [DEV-1505] Webinar tests

- .github/workflows/deploy_infra.yml
- Move working-directory to a single step
The deploy_infra workflow gives an error.
> Move working-directory to a single step

- .changeset/eighty-mails-sort.md
> Fix deploy infra workflow changelog

- .changeset/lovely-drinks-mix.md
- apps/nextjs-website/src/components/atoms/SummaryInformation/SummaryInformation.tsx
- apps/nextjs-website/src/components/molecules/WebinarQuestion/WebinarQuestionRow.tsx
- apps/nextjs-website/src/components/organisms/WebinarQuestionsForm/WebinarQuestionsForm.tsx
- apps/nextjs-website/src/components/organisms/WebinarQuestionsTable/WebinarQuestionsTable.tsx
- apps/nextjs-website/src/components/organisms/WebinarQuestionsTemplate/WebinarQuestionsTemplate.tsx
- apps/nextjs-website/src/config.ts
- apps/nextjs-website/src/messages/it.json
Webinar page
- move the SEND button to the right
- set question's maximum lenght to 240 characters
Questions page
- set the name of the person highlighting a question as visible to himself
- decrease fetchWebinarsQuestionsIntervalMs
- move the highlighted questions to a column on the right
- set tables to fit the available width
- hide hidden questions to the other users
Manually
**webinar page**
**webinar questions page**
with a user
with another user
> [DEV-1515] Fix webinar form and webinar questions page

- .changeset/popular-readers-crash.md
- apps/nextjs-website/src/_contents/webinars.ts
> [DEV-1534] Update webinar timing

- .changeset/five-garlics-mix.md
- apps/infrastructure/src/acm.tf
- apps/infrastructure/src/cloudfront.tf
- apps/infrastructure/src/route53.tf
Create DNS for the Strapi Media Library
- Create SSL certificate for `cdn.developer.pagopa.it`
- Create DNS records for validation
- Link the Media Library's CDN to the domain
We want to access the assets through a DNS owned by PagoPA
> [DEV-1529] Create DNS for the CMS Media Library

- .changeset/thin-games-promise.md
- apps/nextjs-website/src/_contents/webinars.ts
Update video on demand src
because vimeo change the src for the video
> [DPC-194] Update video on demand src

- .changeset/shiny-comics-allow.md
- apps/nextjs-website/src/_contents/webinars.ts
Reverts pagopa/developer-portal#761
> Revert "[DPC-194] Update video on demand src"

- .changeset/silly-forks-shake.md
- apps/infrastructure/src/cloudfront.tf
- apps/infrastructure/src/route53.tf
Let the domain cdn.dev.developer.pagopa.it to be reachable.
- Add alias to the CDN
- Add A record to Route53
We need to reach the CDN through our custom domain.
Running `terraform plan` through the CI.
Running a `terraform apply` from a local machine.
Before this PR, the asset on https://cdn.dev.developer.pagopa.it/hero_swiper_8cd4b232cb.png is not available.
After this PR, it will be possible to reach that asset.
> [DEV-1538] Reach Media Library CDN using custom domain

- .changeset/purple-goats-occur.md
- apps/infrastructure/src/ecs.tf
Depends on #766 
Update the URL of the CDN (Media Library)
We want the assets to be accessible to a custom domain
> [DEV-1472] Update CDN url in task definition

- .changeset/lucky-buses-give.md
- apps/infrastructure/src/cloudfront.tf
Add the *.developer.pagopa.it domain to the CSP
We need to fetch assets from our CDN.
> [DEV-1543] Allow fetching images from devportal domains

- .changeset/rare-baboons-brake.md
- apps/nextjs-website/src/_contents/webinars.ts
Set endDateTime of 'always-live' webinar to year 2077
The team needs the always-live webinar to be always in live state for test purposes
Manually
> [DEV-1550] Set endDateTime of 'always-live' webinar to year 2077

- .changeset/loud-beans-hang.md
- apps/infrastructure/src/sns_topic.tf
Create the SNS topic and the subscription used to send alerts to an email address.
- Create the SNS topic
- Create the SNS subscription
- Add details of where the alerts should be delivered
We want to be notified in case of some alerts are activated.
> [DEV-1345] Create SNS topic and subscriptions for metric alarms

- .changeset/clever-toes-think.md
- apps/nextjs-website/src/_contents/webinars.ts
Change in subtitle for webinar
Because it's the same title
> [DPC-187] Change in subtitle for webinar

- .changeset/orange-candles-learn.md
- apps/strapi-cms/src/api/homepage/content-types/homepage/schema.json
> [DEV-1524] webinars backend

- .changeset/breezy-mails-fetch.md
- apps/infrastructure/src/task-definitions/cms_app.json.tpl
Move parameter store secrets from environment to secrets section
The values on secrets are translated from `arn` to `value`. Without this changes some secret were not translated to `value` because where on environment sections.
N/A
> [DEV-1562] Move parameters to secrets section

- .changeset/green-buses-kick.md
- apps/infrastructure/src/task-definitions/cms_app.json.tpl
Replace `value` with `valueFrom` on some secret variables
The secrets variables should have `valueFrom` if the `arn` is provided
N/A
> [DEV-1562] Fix cms task definition template secret values

- .changeset/afraid-dingos-agree.md
- apps/nextjs-website/src/_contents/webinars.ts
> Fix vimeo id for 'Esplorando App IO: I messaggi a contenuto remoto' webinar

- .changeset/many-onions-explain.md
- apps/infrastructure/src/ecs.tf
Change `desired_count` of cms-ecs in production, increasing it from 0 to 1
The CMS in production is currently powered off. After this commit, it will be accessible.
N/A
> [DEV-1574] Increase `desired_count` of cms-ecs in production

- .changeset/clever-goats-invent.md
- apps/infrastructure/src/ecs.tf
Ignore changes on task definition
We don't want to downgrade the task-definition if the version from Terraform state differs after an execution of the Deploy CMS workflow
> [DEV-1464] Ignore Task Definition changes

- .changeset/warm-carrots-bathe.md
- apps/infrastructure/src/cloudfront.tf
Added `https://player.vimeo.com/` to CSP entries
To fix follow error:
> Refused to frame 'https://player.vimeo.com/' because it violates the following Content Security Policy directive: "frame-src ...".
> [DEV-1587] Add player.vimeo.com domain to CSP

- .github/CODEOWNERS
Update CODEOWNERS file
Allow to merge the PR opened by [changesets](https://github.com/changesets/changesets)
N/A
> [DEV-1588] Update codeowners file

- .changeset/giant-buttons-develop.md
- apps/nextjs-website/src/components/atoms/WebinarHeaderBanner/WebinarHeaderBanner.tsx
Sorted banner webinars by start time
> [DEV-1595] sort webinars

- .changeset/clever-toes-sip.md
- apps/nextjs-website/src/components/atoms/DesktopUserInfo/DesktopUserInfo.tsx
- Encode `redirect` qs value in `apps/nextjs-website/src/components/atoms/DesktopUserInfo/DesktopUserInfo.tsx`
This change is necessary because if the user starts the login flow from any page other than the home page, after successfully logging in, they will not be redirected to the page from which the flow was started.
Starts login flow from any page from any page other than the home page ([example](https://dev.developer.pagopa.it/webinars/PagoPALab-tari)) and after successfully logging in, you will be redirected to the page from which the flow was started ([example](https://dev.developer.pagopa.it/webinars/PagoPALab-tari)).
1. Go [here](https://dev.developer.pagopa.it/webinars/PagoPALab-tari)
2. Log in
3. Confirm login
4. Automatically return …
> [DEV-1533] Redirect after successful login

- .changeset/gentle-frogs-hammer.md
- apps/nextjs-website/src/components/molecules/WebinarCard/WebinarCard.tsx
* Align webinars speakers' box
The webinars speakers' box was misaligned between different cards
> [DEV-1597]: Align webinars speakers' box

- .changeset/sour-hounds-type.md
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/attributes.ts
Transform URL such as
`https://app.gitbook.com/s/u6YdY319vyFX9MIvnKBa/conto-corrente-alternativo`
to
`https://developer.pagopa.it/pago-pa/guides/metadata/conto-corrente-alternativo`
Run `nvm use 18.16.0; reset; npm run compile; npm run test -w gitbook-docs -- parseContent.test.ts --watch`
Before:
After:
> [DEV-1624] Add app.gitbook.com domain to regular expression during parsing

- .changeset/cold-kids-sleep.md
- apps/nextjs-website/src/_contents/pagoPa/guideLists.ts
- apps/nextjs-website/src/_contents/pagoPa/guides.ts
This PR depends on #846 
Change the main version of SACI and update the corresponding title
SACI update
Locally, Manually
> [DPC-218] Update SACI version

- .changeset/cold-kids-sleep.md
- .changeset/light-terms-sniff.md
- apps/nextjs-website/src/_contents/pagoPa/guideLists.ts
- apps/nextjs-website/src/_contents/pagoPa/guides.ts
This PR depends on #846 
Change the main version of SANP and update the corresponding name in the guide list
SANP update
Locally, Manually
> [DPC-217] Update SANP version

- .changeset/pretty-kings-wave.md
- apps/nextjs-website/src/_contents/products.ts
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/attributes.ts
Gitbook  changed export to md strategy and the link led to the login page of the Selfcare backoffice. 
Running tests: `nvm use 18.16.0; reset; npm run compile; npm run test`
> [DEV-1625] Fix links to selfcare backoffice

- .changeset/serious-snakes-enjoy.md
- apps/nextjs-website/src/_contents/send/guides.ts
Add versions 2.3 and 2.4 to the SEND Knowledge Base. 
Both have been released
Locally/Manually. Path for testing /send/guides/knowledge-base/v2.4 and /send/guides/knowledge-base/v2.3
> [DPC-221] Add 2 new versions for KB SEND

- .changeset/nice-birds-provide.md
- apps/infrastructure/src/iam_role.tf
Update devportal_authenticated_user IAM role
The devportal_authenticated_user IAM role was missing permissions to view, add and delete webinars subscriptions
> [DEV-1636]: Update devportal_authenticated_user IAM role

- .changeset/large-pots-count.md
- apps/nextjs-website/src/_contents/appIo/guides.ts
- apps/nextjs-website/src/_contents/webinars.ts
Change the last version for "Manuale dei Servizi" and modify 1 href on the webinar page accordingly to the changes
Because a new version has been released
locally/manually
> [DPC-225] Version update "Manuale Servizi". IO

- .changeset/thirty-fireants-deny.md
> [DEV-1638] Fix thirty-fireants-deny.md

- .changeset/khaki-pears-applaud.md
- apps/nextjs-website/src/components/organisms/WebinarDetailTemplate/WebinarDetailTemplate.tsx
Add right direction on webinar's paragraphs
The webinars' paragraphs was not rendered correctly
Manually
> [DEV-1680]: fix webinars paragraphs

- .changeset/orange-cars-switch.md
- apps/strapi-cms/src/api/solutions-list-page/content-types/solutions-list-page/schema.json
- apps/strapi-cms/src/components/common/case-histories.json
Fix Strapi relations naming
The Strapi relations naming on dev and prod environments have a maximum length of 63 charachters
Manually
> [DEV-1686]: fix Strapi relations naming

- .changeset/brave-keys-retire.md
- apps/nextjs-website/src/components/organisms/FutureWebinarsShowcase/FutureWebinarsShowcase.tsx
- apps/nextjs-website/src/components/templates/SolutionPageTemplate/SolutionPageTemplate.tsx
- apps/nextjs-website/src/editorialComponents/Hero/Hero.tsx
- apps/storybook-app/.storybook/main.ts
- apps/storybook-app/package.json
- apps/storybook-app/stories/templates/SolutionPageTemplate.stories.tsx
- package-lock.json
Fix Storybook `.env` error
The Storybook app wasn't loading the `.env` variables, so some stories failed to build
Storybook stories
> [DEV-1688] fix storybook env

- .changeset/pink-parrots-switch.md
- apps/nextjs-website/src/components/organisms/GitBookContent/components/Heading.tsx
Fix anchor position on scroll to prevent headings from ending up below the header menu
When navigating to an anchor link, the title associated with the anchor was hidden by the menu.
Manually
**Before**
[screencast-developer.pagopa.it-2024.06.04-14_50_38.webm](https://github.com/pagopa/developer-portal/assets/39835990/7e01805e-9509-4a45-8783-579bdd459ee3)
**After**
[screencast-localhost_3000-2024.06.04-14_52_14.webm](https://github.com/pagopa/developer-portal/assets/39835990/a2e89a48-092a-409e-9a1e-f946c769b580)
> [DEV-1697] Fix anchor position on scroll

- .changeset/stale-walls-wait.md
- apps/nextjs-website/src/_contents/send/guides.ts
- Inserted new version
- Changed main version
New version released
Manually, locally 
Test Path : localhost:3000/send/guides/manuale-operativo
> [DPC-232] Version update "Manuale Operativo" SEND

- .github/workflows/changelog.yaml
- .github/workflows/move_latest_tag.yaml
move_latest_tag workflow:
- allow the workflow to run manually to set a given tag as the latest
- allow the workflow to run only when triggered by a tag
- allow the workflow to run when the tag is not latest (to avoid recursion)
changelog workflow:
- using `secrets.TAG_GITHUB_PAT` as GITHUB_TOKEN to allow triggering the move_latest_tag workflow
The workflow that moves the latest tag isn't currently triggered correctly. The reason is that [a workflow cannot be triggered when the caller (who generated the tag in this case) makes use of the default github token](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) to avoid recurrent calls.
For this reason, although not ideal, the suggested solution is to use a PAT (personal access …
> [DEV-1733] Fix content deploy action

- .changeset/rude-rings-lie.md
- apps/cognito-functions/src/create-auth-challenge-handler.ts
- apps/infrastructure/src/modules/website/cognito_user.tf
- apps/infrastructure/src/modules/website/variables.tf
- apps/nextjs-website/src/messages/it.json
> [DEV-1729] Set a longer OTP duration

- .changeset/two-papayas-cry.md
- apps/nextjs-website/src/components/atoms/TypographyPart/TypographyPart.tsx
Remove DOMPurify.sanitize from TypographyPart component
The `sanitize is not a function` error:
Running build command
> [DEV-1750] Remove domsanitizer from typography part

- .changeset/nice-pans-applaud.md
- apps/nextjs-website/src/lib/api.ts
Building locally with a published tutorial in CMS
> [DEV-1749] Fix getTutorialPaths output to avoid NormalizeError: Requested and resolved page mismatch

- .changeset/brown-items-pretend.md
- apps/nextjs-website/src/_contents/appIo/overview.ts
Fix lint to "Accordo di adesione"
> [DEV-1762] Fix relatedLink in appIO's overview

- .github/workflows/move_latest_tag.yaml
> Changed trigger and removed fetch-tags option in move latest tag wf

- .changeset/short-boxes-glow.md
- apps/storybook-app/stories/templates/TutorialPageTemplate.stories.tsx
* Add `TutorialPageTemplate` story
The `TutorialPageTemplate` component was missing its story
> [DEV-1699] Add tutorial page template story

- .changeset/rare-wolves-help.md
- apps/strapi-cms/src/api/api-data-list-page/content-types/api-data-list-page/schema.json
- apps/strapi-cms/src/api/api-data-list-page/controllers/api-data-list-page.ts
- apps/strapi-cms/src/api/api-data-list-page/routes/api-data-list-page.ts
- apps/strapi-cms/src/api/api-data-list-page/services/api-data-list-page.ts
- apps/strapi-cms/src/api/api-list-page/controllers/api-list-page.ts
- apps/strapi-cms/src/api/api-list-page/routes/api-list-page.ts
- apps/strapi-cms/src/api/api-list-page/services/api-list-page.ts
Rename ApiListPage to ApiDataListPage
Manually
> [DEV-1763] Rename ApiListPage to ApiDataListPage

- .changeset/tall-maps-float.md
- apps/infrastructure/src/modules/website/lambda.tf
Changed cognito-functions deployment configuration in terraform
Cognito functions are not being updated when code is changed
Successfully deployed in develop environment
> [DEV-1729] Fix cognito-functions deployment

- .changeset/blue-mugs-repeat.md
- apps/nextjs-website/src/components/molecules/SubscribeToWebinar/SubscribeToWebinar.tsx
- apps/nextjs-website/src/helpers/user.helper.ts
Fix user can't change password bug
The user couldn't change password
Manually
> [DEV-1734] fix user can't change password bug

- .changeset/good-ravens-decide.md
- apps/strapi-cms/src/api/solutions-list-page/content-types/solutions-list-page/schema.json
- apps/strapi-cms/src/components/common/features.json
Add `features` field on SolutionsListPage
The `features` field was hardcoded
> [DEV-1693]: add features to SolutionsListPage entity on CMS

- .changeset/witty-walls-jog.md
- apps/nextjs-website/src/components/molecules/DesktopSiteHeader/DesktopSiteHeader.tsx
- apps/nextjs-website/src/components/molecules/MobileSiteHeader/MobileSiteHeader.tsx
- apps/nextjs-website/src/messages/it.json
* Add solutions link
The header was missing the solutions link
Manually
> [DEV-1666]: Add solutions link

- .changeset/moody-icons-search.md
- apps/nextjs-website/src/_contents/appIo/guides.ts
Version Update for "Manuale Servizi"
The new version has been released
Manually, Locally
url: http://localhost:3000/app-io/guides/manuale-servizi
> [DPC-238] Update version "Manuale Servizi"

- .changeset/slimy-carpets-behave.md
- apps/strapi-cms/src/api/solution/content-types/solution/schema.json
Add introductionToSteps field to Solution's schema
Manually
> [DEV-1770] Add introductionToSteps field to Solution's schema

- .changeset/warm-yaks-compete.md
- apps/nextjs-website/src/_contents/appIo/guideLists.ts
text reduction
Reduction of the text character count to ensure proper card display
Reduction of the text character count to ensure proper card display
Locally
> [DPC-208] Text reduction

- .changeset/three-bikes-wave.md
- apps/nextjs-website/src/lib/strapi/__tests__/homepage.test.ts
> [DEV-1767] Add test to homepage

- .changeset/pink-meals-nail.md
- apps/nextjs-website/src/_contents/pagoPa/guides.ts
Adds version 3.3.0
released new version
Locally
http://localhost:3000/pago-pa/guides/avviso-pagamento/
> [DPC-239] Version update for "Avvisi di pagamento"

- .changeset/twenty-forks-reflect.md
- apps/nextjs-website/src/components/atoms/CtaCard/CtaCard.tsx
Fix margin on solution list card labels
Before:
After:
> [DEV-1777] Fix margin on solution list card labels

- .changeset/eighty-oranges-relax.md
- apps/strapi-cms/src/api/product/content-types/product/schema.json
- apps/strapi-cms/src/api/solution/content-types/solution/schema.json
- apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
Fix the type of the relations between solutions-products and solutions-webinars
The relations were exclusive
Before:
After:
> [DEV-1781] Fix the type of the relations between solutions-products and solutions-webinars

- .changeset/three-schools-melt.md
- apps/strapi-cms/src/api/product/content-types/product/schema.json
Add shortName to Product schema
The short name is needed in labels
> [DEV-1779] Add shortName to Product schema

- .changeset/early-spiders-trade.md
- apps/strapi-cms/src/api/api-data/content-types/api-data/schema.json
- apps/strapi-cms/src/components/api/api-rest-detail.json
- apps/strapi-cms/src/components/api/spec-urls.json
ApiData model has been updated to show specUrls or soap documentation
This update is needed to complete [DEV-1768]
On strapi
[DEV-1768]: https://pagopa.atlassian.net/browse/DEV-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-1784] update api data model

- .changeset/odd-rice-hug.md
- apps/strapi-cms/src/api/solution/content-types/solution/schema.json
Add solution's steps maximum value
The solution's steps should have a maximum value
> [DEV-1774]: Add solution's steps maximum value

- .changeset/lazy-balloons-knock.md
> Modified chatbot changeset from major to minor

- .changeset/slimy-pens-call.md
- README.md
- apps/nextjs-website/src/__tests__/helpers/productHeader.helpers.test.ts
- apps/nextjs-website/src/_contents/appIo/appIo.ts
- apps/nextjs-website/src/_contents/ioSign/ioSign.ts
- apps/nextjs-website/src/_contents/pagoPa/pagoPa.ts
- apps/nextjs-website/src/_contents/pdnd/pdnd.ts
- apps/nextjs-website/src/_contents/send/send.ts
- apps/nextjs-website/src/components/templates/SolutionPageTemplate/SolutionPageTemplate.tsx
- apps/nextjs-website/src/lib/solutions.ts
- apps/nextjs-website/src/lib/solutionsList.ts
- apps/nextjs-website/src/lib/strapi/__tests__/homepage.test.ts
- apps/nextjs-website/src/lib/strapi/__tests__/quickStarts.test.ts
- apps/nextjs-website/src/lib/strapi/__tests__/tutorials.test.ts
- apps/nextjs-website/src/lib/strapi/codecs/ProductCodec.ts
- apps/nextjs-website/src/lib/types/product.ts
Products labels were too lon
Manually
Before:
After:
> [DEV-1780] Add shortName to Product and use it in product's labels

- .changeset/sweet-months-think.md
- apps/nextjs-website/src/app/[productSlug]/api/[apiDataSlug]/page.tsx
- apps/nextjs-website/src/app/[productSlug]/api/page.tsx
- apps/nextjs-website/src/components/templates/ApiDataListPageTemplate/ApiDataListPageTemplate.tsx
- apps/nextjs-website/src/lib/api.ts
- apps/nextjs-website/src/lib/cmsApi.ts
- apps/nextjs-website/src/lib/types/apiDataParams.ts
Fix ApiPage generateStaticParams
There was an error with the ApiDataPage's `generateStaticParams` function
Manually
> [DEV-1788] Fix ApiDataPage generateStaticParams

- .changeset/stale-colts-breathe.md
- apps/nextjs-website/src/components/templates/ApiDataListPageTemplate/ApiDataListPageTemplate.tsx
- apps/nextjs-website/src/messages/it.json
Fix label "Esplora le API" in ApiDataListPage
The label was the default one
Manually
Before:
After:
> [DEV-1789] Fix label "Esplora le API" in ApiDataListPage

- .changeset/clever-sheep-think.md
- apps/nextjs-website/src/messages/it.json
Fix solution CTA 
The current CTA text is different from [Figma](https://www.figma.com/design/fQkOTQmYbcLVOdZ6NRjVXf/24-Q1-e-Q2---DevPortal?node-id=570-18030&t=ygYA2lvnKHv8eZdv-4)
On [localhost](http://localhost:3000/solutions/)
> [DEV-1791] Fix solution CTA text

- .changeset/shy-jeans-vanish.md
- apps/nextjs-website/src/_contents/translations.ts
- apps/nextjs-website/src/lib/homepage.ts
BUGFIX: add /overview to product links in ecosystem
Product buttons are not working correctly
on localhost
> [DEV-1802] fix product link in ecosystem

- .changeset/shy-books-peel.md
- apps/nextjs-website/src/components/organisms/FutureWebinarsShowcase/FutureWebinarsShowcase.tsx
- apps/nextjs-website/src/components/templates/SolutionPageTemplate/SolutionPageTemplate.tsx
- apps/nextjs-website/src/messages/it.json
Fix solution webinars title
The webinar section on the solution page had the wrong title and description
Manually
> [DEV-1793] Fix solution webinars title

- .changeset/tidy-impalas-switch.md
- apps/nextjs-website/src/components/molecules/ApiSection/ApiSection.tsx
Add border top to Api Section
The border was missing
Localhost
> [DEV-1716] Add border top to Api Section

- .changeset/green-toys-add.md
- apps/nextjs-website/src/app/[productSlug]/tutorials/[...productTutorialPage]/page.tsx
- apps/nextjs-website/src/components/templates/TutorialPageTemplate/TutorialPageTemplate.tsx
- apps/nextjs-website/src/lib/strapi/__tests__/tutorials.test.ts
- apps/nextjs-website/src/lib/strapi/tutorial.ts
- apps/nextjs-website/src/lib/tutorials.ts
- apps/nextjs-website/src/lib/types/tutorialData.ts
Add parts on tutorials on FE
The tutorials used `content` but it was missing some implementations
Manually
> [DEV-1787] Add parts on tutorials on FE

- .changeset/giant-baboons-end.md
- apps/nextjs-website/src/app/[productSlug]/api/page.tsx
- apps/nextjs-website/src/app/[productSlug]/tutorials/[...productTutorialPage]/page.tsx
- apps/nextjs-website/src/components/templates/ApiDataListTemplate/ApiDataListTemplate.tsx
- apps/nextjs-website/src/components/templates/TutorialTemplate/TutorialTemplate.tsx
- apps/nextjs-website/src/lib/apiDataListPages.ts
- apps/storybook-app/stories/templates/ApiDataListTemplate.stories.tsx
- apps/storybook-app/stories/templates/TutorialPageTemplate.stories.tsx
Remove "page" word from template files
A more consistent naming
Manually
> [DEV-1753] Remove "page" word from template files

- .changeset/dull-hounds-swim.md
- apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
- apps/strapi-cms/src/components/common/resource.json
- apps/strapi-cms/src/components/webinar/related-resources.json
Add relatedResources to Strapi's Webinar entity
The attribute was missing
Manually
Content-Type Builder:
Content:
> [DEV-1809] Add relatedResources to Strapi's Webinar entity

- .changeset/new-forks-call.md
- apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
- apps/strapi-cms/src/components/common/question-and-answer.json
- Add QuestionAndAnswer component
- Add questionsAndAnswers field to Webinar schema
The field was missing
Manually
> [DEV-1808] Add questionsAndAnswers field to Webinar schema in Strapi CMS

- .changeset/moody-bulldogs-argue.md
- apps/strapi-cms/src/components/parts/alert.json
> [DEV-1837] Set title and text attributes as optional in Alert schema

- .changeset/wet-rocks-prove.md
- apps/nextjs-website/src/components/templates/SolutionTemplate/SolutionTemplate.tsx
Hide stats in solution if not present
There is an empty area if there are no stats
On localhost
BEFORE
AFTER
> [DEV-1829]  Hide stats in solution if not present

- .changeset/quick-tools-guess.md
- apps/nextjs-website/src/lib/strapi/__tests__/homepage.test.ts
- apps/nextjs-website/src/lib/strapi/__tests__/webinars.test.ts
- apps/nextjs-website/src/lib/strapi/homepage.ts
- apps/nextjs-website/src/lib/strapi/solutionListCodec.ts
- apps/nextjs-website/src/lib/strapi/solutionsCodec.ts
- apps/nextjs-website/src/lib/strapi/webinars.ts
Add questionsAndAnswers attribute to Webinar codec
questionsAndAnswers is part of a new webinar's feature
`npm run test`
> [DEV-1814] Add questionsAndAnswers attribute to Webinar codec

- .changeset/pretty-kids-cheat.md
- apps/storybook-app/stories/templates/SolutionTemplate.stories.tsx
fix product content in solution template
> [DEV-1832] fix solution template product on storybook

- .changeset/funny-penguins-confess.md
- apps/strapi-cms/src/api/solution/content-types/solution/schema.json
Adds case histories to solutions on strapi
Case histories can be accessed inside the solutions
Strapi
> [DEV-1846] Add casehistories to solution schema in strapi

- .changeset/rude-nails-provide.md
- apps/nextjs-website/src/lib/solutions.ts
Fix case histories path
The case histories had a wrong path
Manually
> [DEV-1849]: Fix case histories path

- apps/infrastructure/src/modules/website/lambda.tf
> fix: typo in pre sign-up lambda handler name

- .changeset/big-buckets-hear.md
- apps/strapi-cms/src/api/guide-list-page/content-types/guide-list-page/schema.json
- apps/strapi-cms/src/api/guide-list-page/controllers/guide-list-page.ts
- apps/strapi-cms/src/api/guide-list-page/routes/guide-list-page.ts
- apps/strapi-cms/src/api/guide-list-page/services/guide-list-page.ts
- apps/strapi-cms/src/api/guide/content-types/guide/lifecycles.ts
- apps/strapi-cms/src/api/guide/content-types/guide/schema.json
- apps/strapi-cms/src/api/guide/controllers/guide.ts
- apps/strapi-cms/src/api/guide/routes/guide.ts
- apps/strapi-cms/src/api/guide/services/guide.ts
- apps/strapi-cms/src/components/common/guide-section.json
- apps/strapi-cms/src/components/common/guide-version.json
- apps/strapi-cms/src/components/common/guides-by-category.json
- apps/strapi-cms/src/components/common/list-item.json
Add Guides and GuidesListPage models on strapi
> [DEV-1860] [DEV-1859] Add guides and guides list page on strapi

- .changeset/stale-carrots-relate.md
- apps/strapi-cms/src/api/guide/content-types/guide/schema.json
- apps/strapi-cms/src/components/common/guide-version.json
Fix Guide attribute in Strapi
Fix Guide attribute in Strapi
Manually
> [DEV-1865] Fix guide add product and refactor attribute name

- .changeset/twenty-buttons-work.md
- apps/nextjs-website/src/components/molecules/QuestionsAndAnswers/QuestionsAndAnswers.tsx
- apps/nextjs-website/src/messages/it.json
Add anchor id to QuestionsAndAnswers component
The team needs to directly link Q&A section in webinar pages
Manually
> [DEV-1835] Add anchor id to QuestionsAndAnswers component

- .github/workflows/code_review.yaml
- .github/workflows/pr_enrich.yaml
Adding path filters on unnecessary workflows in changeset PRs
Few workflow should not run for Changeset PRs. The workflow failing causes the CODEOWNERS to not be able to merge the PR although approved.
> [DEV-1853] - Disabled unnecessary actions on changeset PRs

- .github/workflows/code_review.yaml
Conditionally running nextjs website code checks when nextjs files are modified
Some actions are required by branch protection rules to allow PR merges. These actions perform code checks on nextjs-website application and cause PRs of other projects to be slower.
With the previous PR, path filters have been introduced, but, although they are not run anymore, this doesn't prevent the checks to be marked as required causing the PR to be stuck.
[Source](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks):
> [DEV-1853] - Conditionally running nextjs-website checks if files have changed

- apps/chatbot/src/app/main.py
- apps/infrastructure/src/modules/chatbot/api_gateway_rest.tf
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
- apps/infrastructure/src/modules/chatbot/route53.tf
> hotfix: Fix restapi customdomain

- apps/chatbot/src/app/main.py
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
> [CAI-95] - Add list of cors domains to lambda

- .changeset/cold-berries-love.md
- apps/nextjs-website/src/app/[productSlug]/guides/[...productGuidePage]/page.tsx
- apps/nextjs-website/src/lib/cmsApi.ts
Fix Guides page generateStaticParams method
The internal pages were missing
Manually
> [DEV-1909] Fix Guides page generateStaticParams method

- .changeset/odd-timers-dress.md
- apps/strapi-cms/src/api/guide/content-types/guide/schema.json
Fix SEO for guide in strapi
Fix SEO for guide in strapi
Manually
> [DEV-1886] Fix SEO for guide in strapi

- .changeset/clever-flowers-search.md
- apps/nextjs-website/src/app/[productSlug]/tutorials/page.tsx
- apps/nextjs-website/src/components/atoms/AlertPart/AlertPart.tsx
- apps/nextjs-website/src/components/molecules/CkEditorPart/CkEditorPart.tsx
- apps/nextjs-website/src/components/templates/TutorialTemplate/TutorialTemplate.tsx
Add style to content generated with CKEditor in Strapi
Manually
> [DEV-1916] Add style to content generated with CKEditor in Strapi

- .changeset/ten-knives-worry.md
- apps/nextjs-website/src/components/atoms/Stats/Stats.tsx
Fix Stats component layout in Solution's page
Manually and with Storybook
Before:
After:
With one item:
With two items:
With three items:
> [DEV-1946] Fix Stats component layout in Solution's page

- .github/workflows/move_latest_tag.yaml
> [DEV-1924] - Filtering only nextjs tags when moving to latest

- .changeset/funny-pans-joke.md
- apps/strapi-cms/src/api/api-data/content-types/api-data/schema.json
Add product to ApiData
Add product to ApiData
Manually
> [DEV-1933] Add product to api data

- .changeset/tidy-trains-shake.md
- apps/strapi-cms/src/components/api/api-rest-detail.json
Remove unique validator from api rest detail component because of strapi bug 
https://github.com/strapi/strapi/issues/12541 Strapi does not support it in the current version
> [DEV-1958] Remove strapi unique validator

- .changeset/calm-mice-travel.md
- apps/nextjs-website/src/components/molecules/CkEditorPart/CkEditorPart.tsx
Fix paragraph margins and WordBreak setting in ckEditor tables,
Before:
After:
> [DEV-1963] Fix paragraph margins and WordBreak setting in ckEditor tables

- .changeset/grumpy-plums-cheat.md
- apps/nextjs-website/src/components/templates/SolutionTemplate/SolutionTemplate.tsx
Set conditional visibility of Products section in SolutionTemplate
Without associated products, the Products section title was still displayed on the Solution page
Manually
Before:
After:
> [DEV-1964] Set conditional visibility of Products section in SolutionTemplate

- .changeset/few-dots-breathe.md
- apps/strapi-cms/config/api.ts
Fix Strapi defaultLimit and maxLimit configurations
> [DEV-1965] Fix Strapi defaultLimit and maxLimit configurations

- .changeset/little-colts-impress.md
- apps/nextjs-website/src/components/molecules/CkEditorPart/CkEditorPart.tsx
- apps/nextjs-website/src/components/organisms/GitBookContent/components/Item.tsx
Fix margins and text size of guides and tutorials
Before:
After:
> [DEV-1967] Fix margins and text size of guides and tutorials

- .changeset/dull-items-grow.md
- apps/cloudfront-functions/src/viewer-request-handler.ts
- apps/infrastructure/src/modules/chatbot/data.tf
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
Added eventbridge rule that invokes the lambda every 3 minutes
To avoid cold starts
> [CAI-242] - Keep lambda warm by invoking it every 3 minutes

- .changeset/sixty-books-agree.md
- .gitignore
- apps/chatbot/src/app/main.py
- apps/chatbot/src/modules/chatbot.py
- apps/chatbot/src/modules/vector_database.py
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
Save masked questions and answers using Presidio.
Privacy.
my local environment
> [CAI-162] Chatbot/Save masked questions and answers using Presidio

- apps/chatbot/src/modules/vector_database.py
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
added env vars on lambda function for Mistral on AWS Bedrock
We use Mistral now.
> [CAI-227] chatbot: added env vars on lambda function

- .changeset/hot-plums-serve.md
- apps/infrastructure/src/modules/chatbot/cloudwatch_dashboard.tf
- apps/infrastructure/src/modules/chatbot/cloudwatch_metrics_alarms.tf
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
Added cloudwatch alarms and a dashboard that allows the team to monitor the chatbot main components
It is not currently easy to monitor the incoming requests and api errors
Applied
> Add cloudwatch alarms and dashboards

- .changeset/three-socks-provide.md
- apps/infrastructure/src/env/prod/terraform.tfvars
Enable the creation of the chatbot's infrastructure in production
Almost live 🎉
> [CAI-243] - Enable chatbot infrastructure in production

- apps/chatbot/src/modules/chatbot.py
- apps/chatbot/src/modules/presidio.py
Update default response when the chatbot has no context nodes to generate an answer
Front-end style reasons
> [CAI-244] - Bug fix link in default answer

- apps/infrastructure/src/modules/website/variables.tf
Allow @aizoongroup.com to sign up in the development environment
Aizoongroup will carry out security tests on the code and infrastructure of the developer portal
> Allow aizoongroup domain for security testing

- .changeset/sixty-plants-matter.md
- apps/nextjs-website/src/helpers/chatbot.helper.tsx
Fix button feedback in chat
Feedback in chat are not saved in local storage
Manually
Before:
[Screencast from 12-11-2024 11:54:15.webm](https://github.com/user-attachments/assets/11732e73-feec-43ca-a528-a9cb1e605462)
After:
[Screencast from 12-11-2024 11:54:30.webm](https://github.com/user-attachments/assets/34259a7e-8837-4213-bb98-475ccc9bf097)
> [CAI-264] Fix feedback in chat

- .changeset/ten-trains-grin.md
- package-lock.json
- packages/active-campaign-client/jest.config.ts
- packages/active-campaign-client/package.json
- packages/active-campaign-client/src/__tests__/handlers/addContact.test.ts
- packages/active-campaign-client/src/__tests__/handlers/createList.test.ts
- packages/active-campaign-client/src/__tests__/handlers/deleteContact.test.ts
- packages/active-campaign-client/src/__tests__/handlers/deleteList.test.ts
- packages/active-campaign-client/src/__tests__/handlers/updateContact.test.ts
- packages/active-campaign-client/src/handlers/addContact.ts
- packages/active-campaign-client/src/handlers/createList.ts
- packages/active-campaign-client/src/handlers/deleteContact.ts
- packages/active-campaign-client/src/handlers/deleteList.ts
- packages/active-campaign-client/src/handlers/updateContact.ts
- packages/active-campaign-client/src/index.ts
- packages/active-campaign-client/src/types/webinarPayload.ts
- packages/active-campaign-client/src/utils/activeCampaignClient.ts
Refactor Active Campaign package
> [DEV-2026] Refactor Active Campaign package

- .changeset/soft-socks-build.md
- apps/infrastructure/src/main.tf
- apps/infrastructure/src/modules/chatbot/acm.tf
- apps/infrastructure/src/modules/chatbot/alb.tf
- apps/infrastructure/src/modules/chatbot/cognito_user.tf
- apps/infrastructure/src/modules/chatbot/data.tf
- apps/infrastructure/src/modules/chatbot/ecr.tf
- apps/infrastructure/src/modules/chatbot/ecs.tf
- apps/infrastructure/src/modules/chatbot/iam.tf
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
- apps/infrastructure/src/modules/chatbot/locals.tf
- apps/infrastructure/src/modules/chatbot/rds_aurora.tf
- apps/infrastructure/src/modules/chatbot/route53.tf
- apps/infrastructure/src/modules/chatbot/task-definitions/langfuse.json.tpl
- apps/infrastructure/src/modules/chatbot/variables.tf
- apps/infrastructure/src/modules/cms/outputs.tf
- apps/infrastructure/src/variables.tf
> [CAI-214] Implement langfuse infrastructure

- apps/chatbot/package.json
> [CAI-158] disable chatbot test

- .changeset/smooth-laws-do.md
- .github/workflows/deploy_ac_sync_lambda.yaml
- apps/infrastructure/src/modules/website/iam_policy.tf
> fix: npm install and add permissions to gh actions role

- .changeset/pretty-gorillas-bow.md
- apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
Fix webinar slug validation
Fix webinar slug validation
Manually
> [DEV-2058] Fix webinar slug validation

- .changeset/gorgeous-ghosts-float.md
- apps/infrastructure/src/modules/active_campaign/cloudwatch_metrics_alarms.tf
- apps/infrastructure/src/modules/active_campaign/eventbridge.tf
- apps/infrastructure/src/modules/active_campaign/sqs.tf
- apps/infrastructure/src/modules/cms/ecs.tf
> [DEV-2072] Use the ddb streams event id as SQS message group id

- .changeset/early-kangaroos-accept.md
- apps/nextjs-website/src/app/[productSlug]/guides/[...productGuidePage]/page.tsx
- apps/nextjs-website/src/app/solutions/[solutionSlug]/[...solutionSubPathSlugs]/page.tsx
- apps/nextjs-website/src/lib/cmsApi.ts
- apps/nextjs-website/src/lib/strapi/codecs/UrlReplaceMapCodec.ts
- apps/nextjs-website/src/lib/strapi/fetches/fetchUrlReplaceMap.ts
- Fix UrlReplaceMap codec
- Simplify populate
- Cache the result
Publishing UrlReplaceMap in Strapi breaks guide pages
> [DEV-2088] Fix UrlReplaceMap codec, simplify populate and cache the result

- apps/chatbot/src/app/main.py
question field validation max 800 chars
defend
```
chatbot:chatbot/question-length/» http POST localhost:8080/queries question="012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901 …
```
> [CAI-292] Chatbot/question length

- .github/workflows/deploy_chatbot.yaml
- apps/infrastructure/src/modules/cms/ecs.tf
> Fix chatbot lambda deploy

- .changeset/selfish-clocks-begin.md
- apps/chatbot/scripts/dynamodb-scan-queries.sh
- apps/chatbot/scripts/dynamodb-scan-sessions.sh
- apps/chatbot/src/app/main.py
- apps/chatbot/src/modules/chatbot.py
check userId on sessions query
My sessions are only mine.
locally from swaggerUI
> [CAI-293] Chatbot/fix session query

- .changeset/long-bikes-run.md
- packages/active-campaign-client/src/clients/activeCampaignClient.ts
- packages/active-campaign-client/src/scripts/sync_all_users.ts
- Divede API call in batch
- Add logs
Overcome Active campaing limits
Manually
> [DEV-2108] Add batch import

- .changeset/chilled-bears-act.md
- packages/active-campaign-client/src/handlers/sqsQueueHandler.ts
Fix error management for sqs queue
Correctly populate DLQ queue
Manually
> [DEV-2110] Fix error management for sqs queue

- .github/actions/check-nextjs-bundle-size/action.yaml
- .github/workflows/deploy_ac_sync_lambda.yaml
> fix: update artifacts actions versions

- .github/actions/check-nextjs-bundle-size/action.yaml
> fix: check-nextjs-bundle-size-action

- .changeset/long-ducks-unite.md
- apps/nextjs-website/src/helpers/auth.helpers.ts
- apps/nextjs-website/src/messages/it.json
Fix emailMatcher regular expression in order to allow only lowercase letters
The team needs to prevent users from signing up multiple times by only changing the case of the email address
Before:
After:
> [DEV-2114] signup only with lowercase email

- .github/workflows/deploy_cms.yaml
> fix: update amazon-ecs-deploy-task-definition action

- .github/workflows/deploy_cms.yaml
> fix: ecs-deploy-task-definition version

- .github/actions/check-nextjs-bundle-size/action.yaml
- .github/workflows/code_review.yaml
> fix: artifact name must be unique

- .changeset/sharp-bikes-act.md
- packages/active-campaign-client/src/handlers/sqsQueueHandler.ts
- packages/active-campaign-client/src/helpers/queueEventParser.ts
- packages/active-campaign-client/src/types/queueEvent.ts
Manage DynamoMODIFY event
Manage DynamoMODIFY event to avoid generation of error in DLQ
Manually
> [DEV-2117] Manage DynamoMODIFY event

- .github/actions/check-nextjs-bundle-size/action.yaml
> Include hidden files in NextJS bundle artifact

- .github/actions/chatbot/action.yaml
Restart lambda function after reindex pipeline
clear the cache
> [CAI-63] fix: restart lambda after reindex pipeline

- .changeset/afraid-roses-cry.md
- apps/nextjs-website/src/components/atoms/ChatHistoryMessage/ChatHistoryMessage.tsx
- apps/nextjs-website/src/components/atoms/ChatMessage/ChatMessage.tsx
Add conditional parsing for chat messages
Links sent by the user where parsed and shown in the chat.
On localhost
Before:
After:
> [CAI-296][DEV-2120] Add conditional parsing to chat and history

- .changeset/strange-berries-beam.md
- apps/strapi-cms/src/api/product/content-types/product/schema.json
- apps/strapi-cms/src/api/release-note/content-types/release-note/schema.json
- apps/strapi-cms/src/api/release-note/controllers/release-note.ts
- apps/strapi-cms/src/api/release-note/routes/release-note.ts
- apps/strapi-cms/src/api/release-note/services/release-note.ts
Add ReleaseNote collection to Strapi
Add relation with Product
Manually
> [DEV-2100] Add ReleaseNote collection to Strapi

- .github/actions/chatbot/action.yaml
- .github/workflows/chatbot_reindex.yaml
Fix CHATBOT_LAMBDA_NAME var on pipeline
> [CAI-63] Chatbot/restart lambda after reindex

- .changeset/rare-turtles-prove.md
- apps/nextjs-website/src/app/[productSlug]/overview/page.tsx
- apps/nextjs-website/src/app/page.tsx
- apps/nextjs-website/src/components/atoms/RelatedLinks/RelatedLinks.tsx
- apps/nextjs-website/src/components/molecules/SectionTitle/SectionTitle.tsx
- apps/nextjs-website/src/components/organisms/NewsShowcase/NewsShowcase.tsx
- apps/nextjs-website/src/components/organisms/PostIntegration/PostIntegration.tsx
- apps/nextjs-website/src/components/organisms/TutorialsOverview/TutorialsOverview.tsx
- apps/nextjs-website/src/editorialComponents/Listing/Listing.tsx
- apps/nextjs-website/src/editorialComponents/Newsroom/Newsroom.tsx
- apps/nextjs-website/src/lib/strapi/makeProps/makeHomepage.ts
- apps/nextjs-website/src/lib/strapi/makeProps/makeOverviews.ts
Add whatsNew section to Overview page
Add label to newsItems in home page
To create links to the release notes that will be created thanks to upcoming pull requests
Manually
A page without the new section:
A page with the new section using mock data:
> [DEV-2097][DEV-2098] Add whatsNew section to Overview page

- .changeset/tough-snakes-roll.md
- .github/workflows/code_review_infra.yaml
- .github/workflows/deploy_infra.yml
- .gitmodules
- apps/cloudfront-functions/src/viewer-request-handler.ts
- apps/infrastructure/src/env/dev/terraform.tfvars
- apps/infrastructure/src/env/prod/terraform.tfvars
- apps/infrastructure/src/main.tf
- apps/infrastructure/src/modules/docs_redirect/acm.tf
- apps/infrastructure/src/modules/docs_redirect/cloudfront.tf
- apps/infrastructure/src/modules/docs_redirect/data.tf
- apps/infrastructure/src/modules/docs_redirect/providers.tf
- apps/infrastructure/src/modules/docs_redirect/route53.tf
- apps/infrastructure/src/modules/docs_redirect/variables.tf
- apps/infrastructure/src/variables.tf
Implemented the infrastructure that allows selective redirects from docs.pagopa.it to developer.pagopa.it
> [DEV-2106] docs.pagopa.it redirect base infrastructure

- .changeset/silent-phones-tell.md
- .gitmodules
- apps/infrastructure/src/.terraform.lock.hcl
- apps/infrastructure/src/main.tf
- apps/infrastructure/src/modules/docs_redirect/cloudfront.tf
- apps/infrastructure/src/modules/docs_redirect/variables.tf
> [DEV-2106] - Docs-redirect submodule removed and gotten cf fn code from github

- .changeset/hungry-kids-provide.md
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/parseContent.ts
Change the doc parsing to show images in <td> tags
Images in table are seen as text
On localhost  (images are broken)
> [DEV-2135] fix images in tables

- .changeset/clean-lizards-rescue.md
- apps/nextjs-website/package.json
- apps/nextjs-website/src/components/molecules/HeroSwiper/HeroSwiper.tsx
- package-lock.json
Add autoplay to HeroSwiper in home page
The second and third slides were ignored by most of the users
Manually
[hero-swiper.webm](https://github.com/user-attachments/assets/4598525f-21dc-4c96-85c3-ff9a4839566f)
> [DEV-2152] Add autoplay to HeroSwiper in home page

- .changeset/perfect-kiwis-repair.md
- apps/infrastructure/src/modules/cicd/iam.tf
> Fix CICD lambda permissions

- .changeset/proud-lizards-exist.md
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
> Add GCP project SSM param

- apps/infrastructure/src/modules/chatbot/waf.tf
> [CAI-220] Fix waf rules priorities and apigw association

- .changeset/fluffy-bats-leave.md
- apps/nextjs-website/src/helpers/makeS3Docs.helpers.ts
- apps/nextjs-website/src/helpers/parseS3Doc.helpers.ts
- apps/nextjs-website/src/lib/api.ts
Manually on localhost:
- http://localhost:3000/send/release-note/2024/22-ottobre-2024
- http://localhost:3000/pago-pa/guides/saci/specifiche-attuative-dei-codici-identificativi-di-versamento-riversamento-e-rendicontazione/changelog
- http://localhost:3000/pago-pa/guides/saci/3.0.1/specifiche-attuative-dei-codici-identificativi-di-versamento-riversamento-e-rendicontazione/changelog
> [DEV-2184] Poc standalone fix guide version

- .github/workflows/code_review.yaml
Upgrade actions/cache from version 3.3.1 to version 4.2.2 in code_review workflow
The pipeline checks are failing because of this: https://github.com/actions/toolkit/tree/main/packages/cache
> [DEV-2183] Upgrade actions/cache from version 3.3.1 to version 4.2.2 in code_review workflow

- .changeset/cool-bikes-cheat.md
- apps/nextjs-website/src/components/organisms/GitBookContent/components/Heading.tsx
- packages/gitbook-docs/src/__tests__/parseInPageMenu.test.ts
- packages/gitbook-docs/src/parseInPageMenu.ts
- Fix heading level to variant
- Remove level 3 titles from in-page menu 
Level 3 elements were rendered as H4 headings creating confusion between what should be shown and what should not be shown in the in-page menu on the right.
This markdown: ```### 0101 - **Polizia Locale** ``` should be rendered as h3, not h4
Manually
Before:
After:
> [DEV-2168] Fix heading level to variant

- .changeset/flat-houses-smile.md
- apps/nextjs-website/src/components/molecules/DownloadableDocuments/DownloadableDocuments.tsx
- apps/nextjs-website/src/components/molecules/RelatedResources/RelatedResources.tsx
Fix Downloadable documents title appearance logic
The title used to appear even when it's not necessary
Manually
Before:
After:
> [DEV-2174] Fix Downloadable documents title appearance logic

- .changeset/tough-radios-grin.md
- apps/nextjs-website/src/__tests__/helpers/humanReadableFileSize.helper.test.ts
- apps/nextjs-website/src/components/molecules/DownloadableDocuments/DownloadableDocuments.tsx
- apps/nextjs-website/src/helpers/humanReadableFileSize.helper.ts
- Fix downloadable documents getHumanReadableFileSize
- Add its tests
Before:
After:
> [DEV-2169] Fix downloadable documents getHumanReadableFileSize and add its tests

- .github/workflows/deploy_website.yaml
Fix scheduled deploy permissions
> [DEV-2191] Fix scheduled deploy permissions

- .github/workflows/deploy_website.yaml
Move scheduled deploy to 2 a.m. UTC
> [DEV-2193] Move scheduled deploy to 2 a.m. UTC

- .github/workflows/deploy_website.yaml
- Add missing environment variables for scheduled deploy action
- Move cron to 3 p.m. for test purposes
Manually
> [DEV-2202] Fix environment variables for scheduled deploy action and move cron to 3 p.m. for test purposes

- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
> Add service account parameter and env variable to chatbot lambda

- .changeset/tasty-coats-arrive.md
- apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
Fix webinar slug validator
It is possible to create webinars with an empty slug field
Manually
> [DEV-2154] Fix webinar slug validator

- .github/workflows/deploy_website.yaml
Move scheduled deploy at 11 p.m. UTC (midnight in Rome time)
> [DEV-2203] Move scheduled deploy at 11 p.m. UTC

- .changeset/fuzzy-apples-fetch.md
- apps/nextjs-website/src/components/atoms/DesktopUserInfo/DesktopUserInfo.tsx
Add the cursor pointer to the profile menu
The icon and user's name were clickable, but the cursor was set the wrong way
Manually
> [DEV-1879] Add the cursor pointer to the profile menu

- .changeset/old-colts-greet.md
- apps/strapi-cms/src/api/webinar/content-types/webinar/schema.json
Remove the maximum question and answer limit from the Webinar schema
The team needs to show more than 10 questions
> [DEV-2234] Remove the maximum question and answer limit from the Webinar schema

- .changeset/mighty-ties-hear.md
- .changeset/tasty-toes-drop.md
Fix changeset files
Resolve conflict and run changeset workflow
> [CAI-375] Fix changeset files

- .github/workflows/changelog.yaml
Allow manual trigger of changelog update from GitHub UI
the workflow was executed only when a commit was pushed to the main branch
> [DEV-2249] Allow manual trigger of changelog update from GitHub UI

- .changeset/swift-flowers-pay.md
- apps/infrastructure/src/modules/chatbot/bedrock.tf
- apps/infrastructure/src/modules/chatbot/data.tf
- apps/infrastructure/src/modules/chatbot/ecs.tf
- apps/infrastructure/src/modules/chatbot/locals.tf
- apps/infrastructure/src/modules/cicd/codebuild.tf
- apps/infrastructure/src/modules/cicd/iam.tf
- apps/infrastructure/src/modules/cms/ecs.tf
> Disabled ECS autoscaling in dev and align resources

- .changeset/rude-cups-love.md
- apps/infrastructure/src/modules/chatbot/api_gateway_rest.tf
- apps/infrastructure/src/modules/chatbot/cloudwatch_dashboard.tf
- apps/infrastructure/src/modules/chatbot/cloudwatch_metrics_alarms.tf
- apps/infrastructure/src/modules/chatbot/ecr.tf
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
- apps/infrastructure/src/modules/chatbot/moved.tf
- apps/infrastructure/src/modules/chatbot/outputs.tf
The chatbot lambda function is created using the standard terraform module used for all lambda functions. The key difference is in the deployment method, which for the chatbot is based on a Docker image rather than a code package like all the others. When we release the chatbot, the new image is tagged with the commit SHA. However, the module requires the Docker image URI with a tag. The tag was set to 'latest', so with each terraform apply, the image gets reset to 'latest' (which is often an outdated version).
I see two possible solutions:
- Tag the chatbot image with both the SHA and 'latest' (moving the latest tag forward with each release, similar to what was done for the nextjs-website)
- Rewrite the lambda terraform configuration using direct resources instead of the module. In …
> Extracted chatbot lambda resources from the module

- .changeset/curly-ravens-deny.md
- apps/infrastructure/src/modules/website/iam_policy.tf
> Fix website bucket policy

- .changeset/green-spiders-march.md
- apps/strapi-cms/src/api/webinar/content-types/webinar/lifecycles.ts
Fix webinar slug validation
Validation was preventing webinar publishing
Manually
Before:
> [DEV-2281] Fix webinar slug validation

- .changeset/tame-pillows-carry.md
- apps/strapi-cms/src/api/webinar-category/content-types/webinar-category/schema.json
Remove the "files" option from webinar category icon format
User could add something that wasn't an image to the icon field
Localhost
> [DEV-2287] fix webinar category icon format

- .changeset/rich-baboons-give.md
- apps/infrastructure/src/modules/cms/ecs.tf
> [DEV-2288] Cms ecs update min and max number of tasks for production

- apps/infrastructure/src/env/dev/terraform.tfvars
- apps/infrastructure/src/env/prod/terraform.tfvars
- apps/infrastructure/src/main.tf
- apps/infrastructure/src/modules/cms/rds_aurora.tf
- apps/infrastructure/src/modules/cms/variables.tf
- apps/infrastructure/src/variables.tf
> [DEV-2288] RDS increase production scaling capacity

- .changeset/three-students-sneeze.md
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/parseContent.ts
Fix tag file parsing
Before:
After:
> [DEV-2291] Fix tag file parsing

- .changeset/fluffy-pillows-switch.md
- .github/actions/build-nextjs-website/action.yaml
- .github/actions/deploy/action.yaml
- .github/workflows/chatbot_reindex.yaml
- .github/workflows/code_review.yaml
- .github/workflows/deploy_website.yaml
- .github/workflows/deploy_website_content.yaml
- apps/nextjs-website/.env.default
- apps/nextjs-website/src/app/layout.tsx
- apps/nextjs-website/src/config.ts
Make matomo cookie script retrocompatible
Manually
> [DEV-2293] make matomo cookie script retrocompatible

- .changeset/tricky-badgers-marry.md
- apps/nextjs-website/src/app/layout.tsx
Remove comments from Matomo Tag Manager script and fix indentation
Remove usless comments and test scheduled deploy
> [DEV-2303] Remove comments from Matomo Tag Manager script and fix indentation

- .github/workflows/deploy_standalone.yaml
> [POC] Draft github action to deploy standalone website

- .changeset/gold-rockets-wink.md
- packages/gitbook-docs/src/__tests__/parseContent.test.ts
- packages/gitbook-docs/src/markdoc/attributes.ts
Fix absolute url path transform
Adding a test `npm run test -w gitbook-docs -- --watch`
> [DEV-2324] Fix absolute url path transform

- apps/infrastructure/src/modules/website/README.md
- apps/infrastructure/src/modules/website/opennext.tf
- apps/infrastructure/src/modules/website/variables.tf
> [DEV-2359] New env variable for next app

- apps/infrastructure/src/modules/cms/iam_policy.tf
> fix: Update ecs iam policy to read secret secret chb_strapi_api_key

- apps/infrastructure/src/modules/chatbot/README.md
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
- apps/infrastructure/src/modules/cms/README.md
- apps/infrastructure/src/modules/cms/ecs.tf
- apps/infrastructure/src/modules/cms/iam_policy.tf
- apps/infrastructure/src/modules/cms/ssm_parameter.tf
- apps/infrastructure/src/modules/cms/task-definitions/cms_app.json.tpl
> fix: Update lambda function chatbot env variable

- .changeset/sharp-rivers-grow.md
- apps/nextjs-website/src/app/error.tsx
- apps/nextjs-website/src/messages/it.json
Adds a generic error to nextjs-website
this will help the benchmark understand which pages works and which not
Localhost, building the project
> [DEV-2342] Add generic nextjs error

- .changeset/tricky-zoos-agree.md
- apps/chatbot/src/modules/utils.py
Bug fix for bad importing logs
locally
> [CAI-478] Log fix

- .github/workflows/chatbot_reindex.yaml
> feat: Disable chatbot reindex on pull requests

- .changeset/slick-streets-carry.md
- apps/chatbot/src/app/chatbot_init.py
- apps/chatbot/src/app/jwt_check.py
- apps/chatbot/src/app/routers/queries.py
- apps/chatbot/src/app/sessions.py
- apps/chatbot/src/modules/chatbot.py
- apps/chatbot/src/modules/test_chatbot.py
Add diagnostic logs for better debugging
for better debugging
> [CAI-479] - diagnostic logs

- .changeset/smart-chefs-speak.md
- apps/chatbot/src/modules/chatbot.py
Update `chatbot.py` ho handle a possible bug in loading the generated string as a JSON.
> [CAI-480] - Fix bug to load string as json

- .changeset/tame-pans-lay.md
- apps/strapi-cms/src/components/api/api-soap-detail.json
Add pathToWsdlDir and branch attributes in ApiSoapDetail
Manually
> [DEV-2380] Add repositoryPath and branch attributes in ApiSoapDetail

- .github/actions/add-stylesheet-ref-to-wsdl/action.yaml
- .github/workflows/soap_api_repo_sync.yaml
Fix SOAP API workflow
Manually
> [DEV-2406] Fix soap api sync workflow

- apps/infrastructure/src/modules/cicd/main.tf
> Increase codebuild instance size

- apps/infrastructure/src/modules/website/opennext.tf
> [DEV-2437] Renamed ssm paramenter and env var in opennext

- apps/infrastructure/src/modules/website/opennext.tf
> [DEV-2488] Update lambda server env variable value

- apps/infrastructure/src/modules/chatbot/README.md
- apps/infrastructure/src/modules/chatbot/lambda_chatbot.tf
- apps/infrastructure/src/modules/chatbot/sqs.tf
> [CAI-462] Sqs queue to sent metrics into langfuse

- .changeset/flat-rules-deny.md
- apps/chatbot/src/app/routers/queries.py
- apps/chatbot/src/modules/chatbot.py
Updated chatbot.py and queries.py
Bug fix
Locally
> [CAI-502] - Fix typo bug

- .changeset/great-bears-trade.md
- apps/nextjs-website/src/components/organisms/GitBookContent/components/File.tsx
Add marginBottom to component File
Add margin between File components in guide pages
Manually
> [DEV-2304] Fix File GitBook content component margins

- .github/workflows/sync_gitbook_docs.yaml
Fix sync command by adding --size-only param to skip timestamp checks
Considering the date of the cloned files, each file is transferred to the bucket even if it's identical to the previously synced one (git clone resets timestamps).
Running pipeline https://github.com/pagopa/developer-portal/actions/runs/16325038973
> [DEV-2503] Fix sync command

- .github/workflows/deploy_lambda_monitor.yaml
> [CAI-461] Draft action deploy lambda monitor

- .github/workflows/invalidate_cloudfront_asset_bucket_cache.yaml
Add GitHub workflow to invalidate CloudFront asset bucket cache
To erase cache without syncing data or generating json files
> [DEV-2516] Add GitHub workflow to invalidate CloudFront asset bucket cache

- .changeset/twenty-pens-write.md
- packages/gitbook-docs/src/helpers/fetchFromStrapi.ts
- packages/gitbook-docs/src/scripts/generateGuidesMetadata.ts
- packages/gitbook-docs/src/scripts/generateReleaseNotesMetadata.ts
- packages/gitbook-docs/src/scripts/generateSoapApiRepositoriesList.ts
- packages/gitbook-docs/src/scripts/generateSolutionsMetadata.ts
Fix fetchFromStrapi type to return Error
Fix typos
The pipeline was successful even in the event of an error
Manually running pipeline
> [DEV-2515] Fix generate metadata scripts

- .changeset/cold-oranges-refuse.md
- packages/gitbook-docs/src/scripts/generateReleaseNotesMetadata.ts
- packages/gitbook-docs/src/scripts/generateSolutionsMetadata.ts
Add filters to exclude reusable content from metadata
Manually
> [DEV-2534] Add filters to exclude reusable content from metadata

- package-lock.json
- package.json
- turbo.json
Upgrade turbo to version 2.5.5 with `npx @turbo/codemod migrate`
see [Turborepo documentation](https://turborepo.com/docs/crafting-your-repository/upgrading)
Locally executing `npm run compile` and building frontend application
> [DEV-2310] Upgrade turbo to version 2.5.5

- .changeset/thin-monkeys-report.md
- .github/workflows/chatbot_reindex.yaml
- apps/infrastructure/src/modules/cicd/iam.tf
> Create chatbot indexing IAM role

- .changeset/fresh-emus-shake.md
- .github/workflows/chatbot_reindex.yaml
- apps/infrastructure/src/main.tf
- apps/infrastructure/src/modules/cicd/iam.tf
- apps/infrastructure/src/modules/cicd/variables.tf
- apps/infrastructure/src/modules/website/outputs.tf
> Fix chatbot reindex permissions

- .changeset/shaky-bats-boil.md
- .gitmodules
Remove submodule: apps/nextjs-website/.tmp-docs
The feature was deprecated
> [DEV-2546] Remove submodule: apps/nextjs-website/.tmp-docs

- .github/workflows/chatbot_reindex.yaml
- .github/workflows/sync_gitbook_docs.yaml
Fix reference to environment for pipeline
> [CAI-535] fix reference to environment

- .changeset/empty-tigers-say.md
- apps/nextjs-website/src/lib/strapi/__tests__/factories/guideListPages.ts
- apps/nextjs-website/src/lib/strapi/__tests__/fixtures/guideListPages.ts
- apps/nextjs-website/src/lib/strapi/__tests__/makeGuideListPageProps.test.ts
Rename guideLists fixtures and factories file names to guideListPages
Manually
> [DEV-2696] Rename guideLists fixtures and factories file names to guideListPages

- .changeset/dry-clouds-begin.md
- apps/infrastructure/src/modules/chatbot/lambda_evaluate.tf
> [CAI-585] Update lambda evaluate timeout

- .changeset/grumpy-teeth-sing.md
- apps/infrastructure/src/modules/website/opennext.tf
> [DEV-2843] Update nodejs runtime for website opennext

- .changeset/brown-feet-smell.md
- .github/workflows/sync_gitbook_docs.yaml
- apps/infrastructure/src/modules/website/iam_policy.tf
> [DEV-2842] Update sync gitbook action

- README.md
Update node link version
Add Compile project command
Fix md linting warning
Manually
> [DEV-2817] Update README

- .github/workflows/code_review.yaml
> [DEV-2698] Test code review without increasing the disk space

- apps/infrastructure/src/modules/chatbot/lambda_chatbot_reindex.tf
> [CAI-603] Update timeout chatbot reindex

- .changeset/vast-spoons-stand.md
- apps/storybook-app/stories/organisms/GitBookContent.stories.tsx
Add gitbookcontent to storybook
it helps with markdown rendering tests
> [DEV-2986] add gitbookcontent to storybook
